Develop
mate-academy/layout_search-bar-airbnb pull request #1064
Opened 2021-12-24 14:48 UTC by Havrysh

- [DEMO LINK](https://Havrysh.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Havrysh.github.io/layout_search-bar-airbnb/report/html_report/)

2021-12-24 17:33 UTC, vkryvytskyy requested changes

2021-12-24 17:33 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://Havrysh.github.io/layout_search-bar-airbnb/)
![image](https://user-images.githubusercontent.com/38065883/147367060-ae42e560-a260-4c4f-8ac6-9a21e4540510.png)
Сейчас на DEMO LINK показывается Readme file
Проверь что для билда gh-pages используется правильная ветка, как показано на видео

https://user-images.githubusercontent.com/38065883/144253618-cab69f76-2bad-470e-a1e4-153a08221108.mov

2021-12-24 17:33 UTC, vkryvytskyy commented on src/index.html
> +          class="Form1">
```suggestion
    <form 
      action="#" 
      method="post" 
      data-qa="big" 
      class="Form1"
    >
```
Форматируй теги таким образом

2021-12-24 17:33 UTC, vkryvytskyy commented on src/style.css
> +.smallBar {
У нас немає ніякого проміжного search, відповідно, чому має бути великий і малий search? У нас є search-input та search-input--small (--small - модифікатор). Тому всі стилі які прописані для “великого” інпуту ми задаємо для всіх інпутів в цілому, а за допомогою модифіктора small міняємо тільки потрібні значення, щоб наш інпут став малим.

2021-12-24 20:09 UTC, Havrysh commented on readme.md
> +- [DEMO LINK](https://Havrysh.github.io/layout_search-bar-airbnb/)
у меня нет такой ветки, при деплое ошибка

2021-12-24 20:10 UTC, Havrysh commented on src/style.css
> +.smallBar {
можете подсказать как это выглядит в коде? не пойму как с модификатором изменить размер для отдельного. элемента?

2021-12-24 20:12 UTC, Havrysh commented on readme.md
> +- [DEMO LINK](https://Havrysh.github.io/layout_search-bar-airbnb/)
<img width="1440" alt="Screen Shot 2021-12-24 at 10 12 09 PM" src="https://user-images.githubusercontent.com/21238164/147371211-e15a625d-0a68-4d75-90c8-d4394ad7c9ed.png">

2021-12-28 12:18 UTC, aliceblunt8 requested changes
сделай еще раз `npm run deploy` и когда появится ветка gh-pages сделай как Вова на видео показал
но перед этим проверь какая у тебя установлена версия ноды (`node -v`) - если выше 14, то тебе нужно переустановить 14 версию
можно тут скачать https://nodejs.org/download/release/v14.16.1/

2021-12-28 12:18 UTC, aliceblunt8 commented on src/index.html
> +      <label class="container1">
```suggestion
    >
      <label class="container1">
```

2021-12-28 12:18 UTC, aliceblunt8 commented on src/index.html
> +      class="Form1"
```suggestion
      class="form"
```

2022-04-18 14:32 UTC, Bohdan-Maksymiuk approved these changes

2024-12-11 13:41 UTC, closed without merging