added solution
mate-academy/layout_search-bar-airbnb pull request #1204
Opened 2022-02-16 19:42 UTC by dmitriy-tverdokhlibov

2022-02-16 19:44 UTC, dmitriy-tverdokhlibov commented
DEMO LINK - https://dmitriy-tverdokhlibov.github.io/layout_search-bar-airbnb/)
TEST REPORT LINK - https://dmitriy-tverdokhlibov.github.io/layout_search-bar-airbnb/report/html_report/)

2022-02-17 09:32 UTC, varseniuk requested changes

2022-02-17 09:32 UTC, varseniuk commented on src/index.html
> +        id="search_bar_1"
Використовуй не id, а класи.
Замість класів search_bar_1 та search_bar_2 створи один загальний клас search_bar, де будуть загальні стилі для обох інпутів, і клас search_bar_small, де будуть класи тільки для маленького. І для маленького використай комбінацію class="search_bar search_bar_small"
Зараз для цих двох класів дублюється багато стилів

2022-02-17 09:32 UTC, varseniuk commented on src/style.css
> +input[id="search_bar_1"]::placeholder {
просто створи клас і використай селектор `.search_bar`

2022-02-17 09:32 UTC, varseniuk commented on src/index.html
> +        class="icon_1"
Зображення лупи краще зробити як background-image для інпута, а не як окремий img

2022-02-17 17:28 UTC, dmitriy-tverdokhlibov commented on src/index.html
> +        id="search_bar_1"
А як зв'язати label c input? Якщо без id

2022-02-17 17:42 UTC, dmitriy-tverdokhlibov commented on src/index.html
> +      data-qa="big"
Ok

2022-02-21 16:32 UTC, vitaliy-martynyuk requested changes
a magnifying glass icon disappears when the input is active 
<img width="325" alt="Screen Shot 2022-02-21 at 6 26 39 PM" src="https://user-images.githubusercontent.com/84335906/154994312-ef9254de-047c-440f-b723-e9948da3d847.png">

2022-02-21 16:32 UTC, vitaliy-martynyuk commented on src/index.html
> +        id="search_bar_1"
there are 2 options:

- place `input` inside `label`
- create `id` for input and `for` for label

[here](https://css-tricks.com/html-inputs-and-labels-a-love-story/#:~:text=There%20are%20two%20ways%20to,input%20and%20holding%20its%20hand.) is a guide for you

2022-02-23 11:30 UTC, vitaliy-martynyuk approved these changes
well done!

2025-04-23 19:06 UTC, closed without merging