solution
mate-academy/layout_search-bar-airbnb pull request #1252
Opened 2022-03-19 10:05 UTC by MelnychukYana

https://MelnychukYana.github.io/layout_search-bar-airbnb/
https://MelnychukYana.github.io/layout_search-bar-airbnb/report/html_report/

2022-03-21 12:17 UTC, marina-tilniak requested changes

2022-03-21 12:17 UTC, marina-tilniak commented on src/style.css
> +.img-s {
in the small search-bar image is a bit smaller. You can specify width for this image

2022-03-21 12:17 UTC, marina-tilniak commented on src/style.css
> +.img-l {
checklist point 2

2022-03-25 17:16 UTC, varseniuk requested changes
Все ок, але варто пофіксити скрізь форматування. Стиль коду - це важливо

2022-03-28 15:31 UTC, vkryvytskyy requested changes

2022-03-28 15:31 UTC, vkryvytskyy commented on src/index.html
> +        >
Эту картинку лучше задавать через background и css. Картинки которые не несут смысловой нагрузки для пользователя не стоит прописывать через тег img(чтобы скрин ридер не зачитывал их, например)

2022-03-28 15:31 UTC, vkryvytskyy commented on src/style.css
> +}
У нас немає ніякого проміжного search, відповідно, чому має бути великий і малий search? У нас є search-input та search-input--small (--small - модифікатор). Тому всі стилі які прописані для “великого” інпуту ми задаємо для всіх інпутів в цілому, а за допомогою модифіктора small міняємо тільки потрібні значення, щоб наш інпут став малим.

2022-03-28 15:31 UTC, vkryvytskyy commented on src/style.css
> +}
Щоб підключити 2 жирності одного шрифта потрібно вказати джерело шрифта, назву шрифта і його жирність.
```
@font-face {
  font-family:  Avenir;
  src: url(/fonts/Avenir-Book.ttf);
  font-weight: 300;
}

@font-face {
  font-family:  Avenir;
  src: url(/fonts/Avenir-Heavy.ttf);
  font-weight: 900;
}
```
Далі можемо використовувати всюди один шрифт Avenir і мати 2 його жирності 300 та 900.

2022-07-21 10:49 UTC, vkryvytskyy requested changes

2022-07-21 10:49 UTC, vkryvytskyy commented on src/style.css
> +}
You haven't fixed this. Please fix and I'll approve it

2022-11-09 19:02 UTC, closed without merging