some message
mate-academy/layout_search-bar-airbnb pull request #1298
Opened 2022-04-03 17:14 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://p-omogit-e.github.io/layout_search-bar-airbnb/report/html_report/)

2022-04-04 11:07 UTC, aliceblunt8 requested changes
- add color to the placeholder from the design, now it differs
- also remove margin-top from the big-search input, cause tests may fallen because of that, add margin to body or the form itself 
<img width="1129" alt="Screenshot 2022-04-04 at 14 06 35" src="https://user-images.githubusercontent.com/57598825/161531376-82454704-0c5b-4d06-8f1f-8b1fd011e8a4.png">

2022-04-04 11:07 UTC, aliceblunt8 commented on src/index.html
> +      >
fix formatting everywhere

```suggestion
        <input 
          name="bigSearch"
          type="search" 
          placeholder="Try &quot;Los Angeles&quot;"
          class="search big-search"
          data-qa="keypress"
      >
```

2022-04-04 11:07 UTC, aliceblunt8 commented on src/index.html
> +    <form data-qa="big" action="hey" method="post">
no need to add in this task

```suggestion
    <form data-qa="big">
```

2022-04-05 07:47 UTC, ArtemTopolskyi approved these changes
Looks good :rocket:

2022-04-05 07:47 UTC, ArtemTopolskyi commented on src/style.css
> +  font-family: Avenir, sans-serif;
это свойство наследуется, можно вынести его в body/html тег

2025-12-17 21:25 UTC, closed without merging