were created search bars
mate-academy/layout_search-bar-airbnb pull request #1366
Opened 2022-05-03 13:58 UTC by KrisMur

- [DEMO LINK](https://KrisMur.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://KrisMur.github.io/layout_search-bar-airbnb/report/html_report/)

2022-05-04 13:12 UTC, mykola-koval requested changes

2022-05-04 13:12 UTC, mykola-koval commented on src/index.html
> +    <div>
do you need this div?

2022-05-04 13:12 UTC, mykola-koval commented on src/index.html
> +        </label>
```suggestion
        <label>
          <img 
            src="images/Search.svg"
            alt="search field"
            class="image"
          >
            
          <input 
            type="search" 
            placeholder="Try &quot;Los Angeles&quot;"
            data-qa="keypress"
            class="searchBig"
          >
        </label>
```

2022-05-04 13:12 UTC, mykola-koval commented on src/style.css
> +}
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/90685701/166687978-7e77ab97-5f0b-49a2-9995-a48666db2082.png">
read through the checklist once more and check if you have any ways to improve the code 
https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md

2022-05-06 07:35 UTC, Olexandr6 approved these changes
Good job🔥

2024-10-19 12:31 UTC, closed without merging