searchbar
mate-academy/layout_search-bar-airbnb pull request #1434
Opened 2022-05-10 12:10 UTC by DmytroSukhaniuk

2022-05-10 17:27 UTC, jstmpelowycz requested changes
1. Не бачу посилань на DEMO та TEST REPORT LINK
2. Відформатуй, будь ласка, код, як показано в чеклісті (це дійсно важливо)

2022-05-11 11:27 UTC, closed without merging

2022-05-12 10:32 UTC, DmytroSukhaniuk commented
додав демо лінк та тест репорт

2022-05-30 17:09 UTC, Serrggii commented
https://Serrggii.github.io/layout_search-bar-airbnb/
https://Serrggii.github.io/layout_search-bar-airbnb/report/html_report/

2022-05-30 19:21 UTC, Serrggii commented
https://Serrggii.github.io/layout_search-bar-airbnb/
https://Serrggii.github.io/layout_search-bar-airbnb/report/html_report/

2022-06-01 00:34 UTC, Naveed-Shoukat commented
https://Naveed-Shoukat.github.io/layout_search-bar-airbnb/
https://Naveed-Shoukat.github.io/layout_search-bar-airbnb/report/html_report/