creating search bar
mate-academy/layout_search-bar-airbnb pull request #1609
Opened 2022-07-06 17:22 UTC by mykola-chernysh

[DEMO LINK](https://mykola-chernysh.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://mykola-chernysh.github.io/layout_search-bar-airbnb/report/html_report/)

2022-07-08 09:56 UTC, valerii-derkach requested changes

2022-07-08 09:56 UTC, valerii-derkach commented on src/style.css
> +  font-family: Avenir, Helvetica, sans-serif;
and here

2022-07-08 09:56 UTC, valerii-derkach commented on src/style.css
> +  font-family: Avenir, Helvetica, sans-serif;
same here

2022-07-08 09:56 UTC, valerii-derkach commented on src/style.css
> +  line-height: 137.5%;
use integers

2022-07-08 09:56 UTC, valerii-derkach commented on src/style.css
> +  line-height: 137.5%;
use integers

2022-07-09 20:03 UTC, marina-tilniak approved these changes

2022-07-09 20:03 UTC, marina-tilniak commented on src/index.html
> +        >
```suggestion
        class="search-image"
      >
```

2023-11-27 09:04 UTC, closed without merging