search-bar
mate-academy/layout_search-bar-airbnb pull request #1736
Opened 2022-07-25 11:21 UTC by dimaus97

- [DEMO LINK](https://dimaus97.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://dimaus97.github.io/layout_search-bar-airbnb/report/html_report/)

2022-07-28 11:06 UTC, Bohdan-Maksymiuk requested changes
you didn't pass any test(
you may try to position elements as in sample https://codepen.io/adskiy/pen/mdmLqXB
and read about right class adding here in 2 point https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md
(there are examples)

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +    <!-- <h1>Search bar airbnb</h1> -->
```suggestion
```

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +    <!-- <h1>Search bar airbnb</h1> -->
```suggestion
```

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          >
```suggestion
            <img 
              src="./images/Search.svg" 
              alt="search-icon"
            >
```

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +            class="input first"
```suggestion
            class="input"
```

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +          class="input second"
```suggestion
          class="input input--small"
```

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
it can be added to the `.input` class

2022-07-28 11:06 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
and it can be transferred to the `.input--small` class

2022-08-02 09:52 UTC, valerii-derkach approved these changes

2026-09-02 08:49 UTC, closed without merging