created 2 search bars
mate-academy/layout_search-bar-airbnb pull request #2137
Opened 2022-10-06 09:39 UTC by halynarydasova

- [DEMO LINK](https://halynarydasova.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://halynarydasova.github.io/layout_search-bar-airbnb/report/html_report/)

2022-10-06 14:56 UTC, amitpatiljc requested changes

2022-10-13 15:51 UTC, jstmpelowycz requested changes
GJ, there is the last thing to fix – font does not get bold on focus

2022-10-13 15:51 UTC, jstmpelowycz commented on src/index.html
> +    >
```suggestion
      <img
        src="images/Search.svg"
        alt="Search"
        class="search-icon search-icon-small"
      >
```

2022-10-13 15:51 UTC, jstmpelowycz commented on src/style.css
> +  padding: 0;
do not put such rules under `*` selector, it could be destructive

2022-10-21 07:35 UTC, closed without merging