commit message
mate-academy/layout_search-bar-airbnb pull request #2221
Opened 2022-10-24 06:43 UTC by Yevhen-Ivanchuk

2022-10-24 17:12 UTC, qoa11a requested changes
Please provide demo link and test report link

2022-10-31 11:48 UTC, Anastasiia-Svintsova requested changes
Still can't see demo link and test report link

2022-11-02 14:39 UTC, Yevhen-Ivanchuk commented
[DEMO LINK](https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/report/html_report/)
- вы об этом?
-

2022-11-02 18:45 UTC, Bohdan-Maksymiuk requested changes
https://user-images.githubusercontent.com/94289038/199574985-9cd213c9-316a-43d3-a66d-7bcdc8c7fe2c.mov

* pay attention to font styles

2022-11-02 18:45 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <input
```suggestion
    <form
      class="form box-big"
      action="#"
      method="post"
      data-qa="big"
    >

      <input
        class="input input-big"
        type="text"
        name="Search"
        placeholder="Try &quot;Los Angeles&quot;"
        data-qa="keypress"
      >
    </form>

    <form
      class="form box-small"
      action="#"
      method="post"
      data-qa="small"
    >
      <input
```

2022-11-02 18:45 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
pay attention to point 2 of [checklist](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md)
you have a lot of repeated styles - fix for another elements

2022-11-24 10:07 UTC, Yevhen-Ivanchuk commented
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/report/html_report/
подскажить почему не проходит один тест?!

2022-11-24 11:22 UTC, qoa11a requested changes
привіт
тест не проходить, тому що іконка розташована трішки нижче та правіше, ніж потрібно

2022-11-24 14:16 UTC, Yevhen-Ivanchuk commented
я понимаю, но другие тесты на data-qa="small" прошли же, почему так?

2022-11-24 14:53 UTC, Yevhen-Ivanchuk commented
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/report/html_report/
не учел паддинги по 1px, дякую!

2022-11-24 19:10 UTC, Viktor-Kost requested changes

2022-11-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +  margin: 20px 0;
You should avoid margin collapsing, when a child margins go through a parent and push off another parent
[useful_link](https://www.smashingmagazine.com/2019/07/margins-in-css/#parent-and-first-or-last-child-element)
So, if you want one element to be push off from another element use margins at THESE elements, not their children

2022-11-24 19:10 UTC, Viktor-Kost commented on src/index.html
> +          type="text"
Use modifiers

```suggestion
      <div class="search search--small">
        <input
          class="input input--small"
          type="text"
```

2022-11-24 19:10 UTC, Viktor-Kost commented on src/style.css
> +  background-repeat: no-repeat;
remove it to block .input

```suggestion
  background-image: url(images/Search.svg);
  background-repeat: no-repeat;
```

2022-12-19 16:21 UTC, Yevhen-Ivanchuk commented
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/
https://Yevhen-Ivanchuk.github.io/layout_search-bar-airbnb/report/html_report/
проверьте пожалуйста

2022-12-19 19:07 UTC, closed without merging

2022-12-20 07:37 UTC, polosanya commented
Why did you ask for a review and close the Pull Request?
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review 🙂

2022-12-20 07:41 UTC, Yevhen-Ivanchuk commented
Какую подписку отменить?
У меня что-то сломалось в VC Code. Хотел пресоздать задание и удалил его,
сейчас решаю проблему и закину новый PR.


вт, 20 дек. 2022 г. в 09:37, Oleksandr Polotniuk ***@***.***>:

> Why did you ask for a review and close the Pull Request?
> If you have any questions, please ask them in fe_chat and tag mentors. It
> will be faster, because your answers in GitHub will be visible to mentor
> only after you re-request review 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_search-bar-airbnb/pull/2221#issuecomment-1358950918>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3H5QVMTRJXDBQDSF7ZA6SLWOFO3XANCNFSM6AAAAAARMVJZEI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>

2022-12-20 07:42 UTC, Yevhen-Ivanchuk commented
Как открыть его обратно, если это так важно?!

2022-12-20 07:42 UTC, Yevhen-Ivanchuk commented
Как открыть его обратно, если это так важно?!


вт, 20 дек. 2022 г. в 09:40, Yevhen Ivanchuk ***@***.***>:

> Какую подписку отменить?
> У меня что-то сломалось в VC Code. Хотел пресоздать задание и удалил его,
> сейчас решаю проблему и закину новый PR.
>
>
> вт, 20 дек. 2022 г. в 09:37, Oleksandr Polotniuk ***@***.***
> >:
>
>> Why did you ask for a review and close the Pull Request?
>> If you have any questions, please ask them in fe_chat and tag mentors. It
>> will be faster, because your answers in GitHub will be visible to mentor
>> only after you re-request review 🙂
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mate-academy/layout_search-bar-airbnb/pull/2221#issuecomment-1358950918>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A3H5QVMTRJXDBQDSF7ZA6SLWOFO3XANCNFSM6AAAAAARMVJZEI>
>> .
>> You are receiving this because you modified the open/close state.Message
>> ID: ***@***.***
>> com>
>>
>

2022-12-21 15:26 UTC, Yevhen-Ivanchuk commented
Какую подписку отменить? У меня что-то сломалось в VC Code. Хотел пресоздать задание и удалил его, сейчас решаю проблему и закину новый PR. Как вернуть все обратно, если это проблема?!