Made a search-bar
mate-academy/layout_search-bar-airbnb pull request #2223
Opened 2022-10-24 11:28 UTC by ia-lerimund

Why does the program not see the bottom border of the second form in tests?

2022-10-25 15:20 UTC, stanislav-topikha requested changes
remove the outline 
![image](https://user-images.githubusercontent.com/99331793/197814361-0432d6ca-ca95-4ebf-97dc-4f4e7b85bdba.png)

and comments ⬇️

2022-10-25 15:20 UTC, stanislav-topikha commented on src/index.html
> +    </form>
```suggestion
    <form 
      action="/" 
      method="get"
      data-qa="big"
    >
      <label class="label" for="search-bar-b">
        <img 
          class="search-icon" 
          src="./images/Search.svg" 
          alt="search-icon">
        <input 
          class="search-bar" 
          type="text" 
          name="search-bar-b" 
          id="search-bar-b"
          placeholder="Try &quot;Los Angeles&quot;"
          data-qa="keypress"
        >
      </label>
    </form>
    <form 
      action="/" 
      method="get"
      data-qa="small"
    >
      <label class="label" for="search-bar-s">
        <img 
          class="search-icon search-icon-small" 
          src="./images/Search.svg" 
          alt="search-icon">
        <input 
          class="search-bar search-bar-small" 
          type="text" 
          name="search-bar-s" 
          id="search-bar-s"
          placeholder="Try &quot;Los Angeles&quot;"
          data-qa="small"
        >
      </label>
    </form>
```

lets make it work like this

2022-10-26 09:34 UTC, stanislav-topikha requested changes

2022-10-26 09:34 UTC, stanislav-topikha commented on src/style.css
> +}
dont use tag selectors

2022-10-26 09:34 UTC, stanislav-topikha commented on src/style.css
> +  font-family: "Avenir", sans-serif;
add fallback font, set it to `html`

2022-10-27 10:17 UTC, stanislav-topikha requested changes
<img width="854" alt="image" src="https://user-images.githubusercontent.com/99331793/198258985-2fce3fc2-2938-46d4-b09a-29380e0892e1.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/99331793/198259013-356eaecd-177e-46e1-929b-319ad5b67499.png">

links dosent work

2022-11-06 13:11 UTC, SanyaBratashchuk approved these changes

2023-04-13 02:14 UTC, closed without merging