search bars task
mate-academy/layout_search-bar-airbnb pull request #2248
Opened 2022-10-26 06:55 UTC by mttony

[DEMO LINK](https://mttony.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://mttony.github.io/layout_search-bar-airbnb/report/html_report/)

2022-10-28 13:31 UTC, liliia-livandovskaya commented on src/style.css
> +  font-family: Avenir, Helvetica, sans-serif;
font should be set in `html` selector tad and inherited where needed

2022-10-28 13:32 UTC, liliia-livandovskaya commented on src/style.css
> +  position: absolute;
```suggestion
```
this is duplicated one

2022-10-28 13:53 UTC, liliia-livandovskaya commented on src/index.html
> +    <form
```suggestion
    </form>
    
    <form 
```

2022-10-28 13:54 UTC, liliia-livandovskaya requested changes
Great job! Let's work on a fix

2022-10-31 16:01 UTC, DarkMistyRoom requested changes
![image](https://user-images.githubusercontent.com/98764641/199053090-a31b8282-25dd-41e3-addf-16051bfa61ea.png)

2022-11-02 09:39 UTC, vlad-demchuk approved these changes
Just check order of css properties🙂
https://codeguide.academy/html-css.html#css-order

2023-09-23 12:11 UTC, closed without merging