Search Bar
mate-academy/layout_search-bar-airbnb pull request #2338
Opened 2022-11-03 14:38 UTC by Dlonls

- [DEMO LINK](https://Dlonls.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Dlonls.github.io/layout_search-bar-airbnb/report/html_report/)

2022-11-03 15:08 UTC, valerii-derkach requested changes
checklist

2022-11-03 15:08 UTC, valerii-derkach commented on src/style.css
> +}
no need default here

use classes as selectors
checklist p1

2022-11-03 15:08 UTC, valerii-derkach commented on src/style.css
> +
checklist p2

2022-11-03 15:08 UTC, valerii-derkach commented on src/style.css
> +  font-family: "Avenir", Arial, Helvetica, sans-serif;
move font family to html tag, and use inheritance where it is needed

2022-11-03 15:08 UTC, valerii-derkach commented on src/style.css
> +  border-radius: 3px;
check font weight on focus, it should be bold

2022-11-04 10:23 UTC, Dlonls commented on src/style.css
> +}
Зробив через класи, але коли прибираю default. Зникає box-shadow.

2022-11-04 12:45 UTC, Ihor-Karpyn approved these changes

2022-12-27 12:55 UTC, closed without merging