Develop
mate-academy/layout_search-bar-airbnb pull request #2378
Opened 2022-11-09 20:23 UTC by RomanHrytsiuk

https://romanhrytsiuk.github.io/layout_search-bar-airbnb/
https://romanhrytsiuk.github.io/layout_search-bar-airbnb/report/html_report/

2022-11-10 14:11 UTC, liliia-livandovskaya requested changes
Remove this blue border <img width="1512" alt="Screenshot 2022-11-10 at 16 11 01" src="https://user-images.githubusercontent.com/104769168/201113949-aa78c1ce-a811-4bd9-a538-dcb372aa81a1.png">

2022-11-10 14:12 UTC, liliia-livandovskaya commented on src/index.html
> +      >
```suggestion
      <img
        class="firstImage"
        src="./images/Search.svg"
        alt="search"
      >
```
fix code style

2022-11-10 14:12 UTC, liliia-livandovskaya commented on src/index.html
> +      <input
```suggestion
      >
      
      <input
```
don't forget to add space between one-level elements

2022-11-10 14:13 UTC, liliia-livandovskaya commented on src/style.css
> +  font-style: normal;
```suggestion
```
its default, remove it

2022-11-10 14:14 UTC, liliia-livandovskaya commented on src/style.css
> +body {
```suggestion
html {
```
font should be set in `html {...}` tag

2022-11-10 14:14 UTC, liliia-livandovskaya requested changes
Great job! Pay attention to the comments

2022-11-11 09:24 UTC, stanislav-topikha requested changes

2022-11-11 09:24 UTC, stanislav-topikha commented on src/index.html
> +      >
```suggestion
    <form
      class="form"
      action="/"
      method="post"
      data-qa="big"
    >
      <img
        class="image"
        src="./images/Search.svg"
        alt="search"
      >

      <input
        type="text"
        class="input"
        placeholder="Try &quot;Los Angeles&quot"
        data-qa="keypress"
      >
    </form>

    <form
      class="form form--small"
      action="/"
      method="post"
      data-qa="small"
    >
      <img
        src="./images/Search.svg"
        alt="search"
        class="image image--small"
      >
      
      <input
        type="text"
        class="input input--small"
        placeholder="Try &quot;Los Angeles&quot"
      >
```
lets make it work like this

2022-11-11 13:05 UTC, stanislav-topikha requested changes

2022-11-11 13:05 UTC, stanislav-topikha commented on src/style.css
> +  border-radius: 4px;
```suggestion
  font-weight: 300;
  height: 42px;
  box-shadow: 0 1px 8px rgba(61, 78, 97, 0.1);
```
recheck repeated styles everywhere, DRY

2022-11-11 14:27 UTC, stanislav-topikha approved these changes
GJ 👍🏻

2024-06-21 08:11 UTC, closed without merging