Develop
mate-academy/layout_search-bar-airbnb pull request #2413
Opened 2022-11-18 09:38 UTC by RatuhWD

2022-11-23 09:15 UTC, RatuhWD commented
- [DEMO LINK](https://RatuhWD.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://RatuhWD.github.io/layout_search-bar-airbnb/report/html_report/)

2022-11-25 08:36 UTC, RatuhWD commented
- [DEMO LINK](https://ratuhwd.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://ratuhwd.github.io/layout_search-bar-airbnb/report/html_report/)

2022-11-25 16:47 UTC, AlisaVlasova requested changes

2022-11-25 16:47 UTC, AlisaVlasova commented on src/style.css
> +  max-width: 1024px;
елемент має бути на весь екран в ширину
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/66749919/204027539-27f437df-c6ab-47bf-a291-ed88cf0b0704.png">

2022-11-25 16:47 UTC, AlisaVlasova commented on src/style.css
> +  font-family: "Avenir-Book", sans-serif;
перенеси в html селектор і додай fallback font

2022-11-25 16:47 UTC, AlisaVlasova commented on src/style.css
> +}
lуже багато стилів посторюються на big i small елементах, додай якісь спільні класи щоб винести в них те, що повторюється

2022-11-25 16:47 UTC, AlisaVlasova commented on src/style.css
> +}
також на фокусі текст інпуту має ставати жирнішим (але не плейсхолдер)
додай стилі також для плейсхолдера щоб зафіксувати font-weight

2022-11-25 16:47 UTC, AlisaVlasova commented on src/index.html
> +          type="submit"
клік на картинку має просто фокусувати на інпуті, а зараз редиректить на 404 сторінку

2023-02-01 14:28 UTC, closed without merging