rostyslav_search-bar-airbnb
mate-academy/layout_search-bar-airbnb pull request #2522
Opened 2022-12-06 19:19 UTC by RostyslavKuts

My work, pls check and say my mistake

2022-12-06 19:22 UTC, RostyslavKuts commented
https://rostyslavkuts.github.io/layout_search-bar-airbnb/

2022-12-06 20:02 UTC, AlisaVlasova requested changes
1. прибери дефолтний аутлайн на інпутах
2. перевір по макету чи правильно ти виставив лупу і падінг

2022-12-06 20:02 UTC, AlisaVlasova commented on src/style.css
> +.small {
зроби спільний клас для обох інпутів і картинок щоб винести стилі що повторюються

2022-12-06 20:02 UTC, AlisaVlasova commented on src/style.css
> +  border-radius: nullpx;
???

2023-02-07 16:26 UTC, AlisaVlasova requested changes
якщо виникають стоппери - звернись у fe_chat2, там швидше вийде розібратись)

2023-02-07 16:26 UTC, AlisaVlasova commented on src/style.css
> +  box-sizing: border-box;
не повторюй всюди box-sizing, задай один раз на селекторі *

2023-02-07 16:26 UTC, AlisaVlasova commented on src/style.css
> +.small {
у класів .small і .big мають дуже багато повторюючихся стилей, додай до обох елементів спільний клас і винеси туди повторення

2023-03-06 10:15 UTC, closed without merging