solution3
mate-academy/layout_search-bar-airbnb pull request #2533
Opened 2022-12-07 15:06 UTC by andriy-chornyy

- [DEMO LINK](https://andriy-chornyy.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://andriy-chornyy.github.io/layout_search-bar-airbnb/report/html_report/)

2022-12-07 16:21 UTC, ArturErmolenko requested changes
input doesn't inherit body font-face, that's why your tests didn't passed

2022-12-08 10:35 UTC, andriy-chornyy commented
> input doesn't inherit body font-face, that's why your tests didn't passed

Я не знаю почему, и не могу исправить без четких указаний, я делаю такое первый раза в жизни

2022-12-09 12:06 UTC, ArturErmolenko commented
> > input doesn't inherit body font-face, that's why your tests didn't passed
> 
> Я не знаю почему, и не могу исправить без четких указаний, я делаю такое первый раза в жизни

пробывал погуглить?

2022-12-09 12:07 UTC, ArturErmolenko requested changes
you need to add fonts on input placeholder

2022-12-09 16:17 UTC, ArturErmolenko requested changes
add this rule

input {
   font: inherit;
 }

2022-12-12 08:13 UTC, alexandra-protyanova commented
<img width="423" alt="Снимок экрана 2022-12-12 в 10 10 42" src="https://user-images.githubusercontent.com/102182808/206994100-c9dfc564-930c-43c6-8668-bacd7c39a9f1.png">
<img width="349" alt="Снимок экрана 2022-12-12 в 10 10 50" src="https://user-images.githubusercontent.com/102182808/206994106-1410c93f-74fa-4dd1-9e84-7f07591c790c.png">
According to mockup height of bars should be `70px` and `42px`

2022-12-12 08:19 UTC, alexandra-protyanova requested changes

2022-12-12 08:19 UTC, alexandra-protyanova commented on src/style.css
> +  font-family: Avenir, sans-serif;
`sans-serif` is odd here

2022-12-12 08:19 UTC, alexandra-protyanova commented on src/style.css
> +  background: #fff;
white - is default color, remove it

2022-12-12 08:19 UTC, alexandra-protyanova commented on src/style.css
> +  font-family: Avenir, sans-serif;
[CHECKLIST](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md) point 7

2022-12-12 14:29 UTC, alexandra-protyanova requested changes

2022-12-12 14:29 UTC, alexandra-protyanova commented on src/style.css
> +}
```suggestion
@font-face {
  font-family: Avenir;
  src: url(./fonts/Avenir-Book.ttf);
  font-style: normal;
  font-weight: 300;
}
```

2022-12-12 14:29 UTC, alexandra-protyanova commented on src/style.css
> +}
```suggestion
@font-face {
  font-family: Avenir;
  src: url(./fonts/Avenir-Book.ttf);
  font-style: normal;
  font-weight: 300;
}
```

2022-12-12 14:29 UTC, alexandra-protyanova commented on src/style.css
> +@font-face {
here you imported font, let us set them to `html` selector and use `inherit` everywhere else

2022-12-12 14:29 UTC, alexandra-protyanova commented on src/style.css
> +.form2 {
do not use numbers in class names

2022-12-12 16:27 UTC, alexandra-protyanova approved these changes

2023-03-01 20:23 UTC, closed without merging