search bar
mate-academy/layout_search-bar-airbnb pull request #2567
Opened 2022-12-15 13:33 UTC by tatiana-sadaeva

2022-12-19 10:47 UTC, tatiana-sadaeva commented
[DEMO LINK](https://tatiana-sadaeva.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://tatiana-sadaeva.github.io/layout_search-bar-airbnb/report/html_report/)

2022-12-21 08:49 UTC, DarkMistyRoom requested changes
Remove this outline
![image](https://user-images.githubusercontent.com/98764641/208859874-ca3e9e8d-89dc-4c05-bd37-01f856bcbc4f.png)

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/index.html
> +    <h1></h1>
```suggestion
```

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/index.html
> +        >
```suggestion
          <img
            src="./images/Search.svg"
            alt="search"
            class="bigButton"
          >
```

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/index.html
> +</html>
add the empty line at the very end

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/style.css
> +} */
remove the comments

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/style.css
> +  box-sizing: border-box;
move `  box-sizing: border-box;` to the `* `selector

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/style.css
> +  font-family: Avenir, sans-serif;
move `font-family` to the `html `selector and inherit where needed

2022-12-21 08:49 UTC, DarkMistyRoom commented on src/style.css
> +}
check the 2nd topic in the checklist. Don't repeat yourself

2022-12-23 15:58 UTC, closed without merging