Develop
mate-academy/layout_search-bar-airbnb pull request #2600
Opened 2022-12-24 12:55 UTC by natalia-matash

- [DEMO LINK](https://natalia-matash.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://natalia-matash.github.io/layout_search-bar-airbnb/report/html_report/)

2022-12-24 19:41 UTC, agniya-i requested changes

2022-12-24 19:41 UTC, agniya-i commented on src/index.html
> +        class="input input_big"
```suggestion
        class="input"
```

2022-12-24 19:41 UTC, agniya-i commented on src/index.html
> +        class="input input_small"
```suggestion
        class="input input--small"
```

2022-12-24 19:41 UTC, agniya-i commented on src/style.css
> +.input_big {
move styles from this class to `.input`, leave only `input--small` to override values for small input (look into checklist p2)

2022-12-26 16:20 UTC, closed without merging

2022-12-26 19:33 UTC, SanyaBratashchuk commented
Why did you close PR?

2022-12-26 19:59 UTC, natalia-matash commented
Because I couldn't change it like in instruction. I saw that PR was
rejected, after I corected mistakes and in MA app PR was still rejected. I
reopened PR, still rejected. So I create new PR.

понедельник, 26 декабря 2022 г. пользователь Sasha Bratashchuk <
***@***.***> написал:

> Why did you close PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_search-bar-airbnb/pull/2600#issuecomment-1365400763>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZ6IIDLHHG2HESZ2HVWDU2DWPHXIVANCNFSM6AAAAAATIOBPCU>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>