Develop
mate-academy/layout_search-bar-airbnb pull request #2604
Opened 2022-12-26 16:21 UTC by natalia-matash

Changed wrong classes and styled it

2022-12-26 19:56 UTC, SanyaBratashchuk requested changes

2022-12-26 19:56 UTC, SanyaBratashchuk commented on src/style.css
> +  font-family: "Averin", sans-serif;
```suggestion
  font-family: inherit;
```
Apply font-family to the `html` tag selector

2022-12-26 19:56 UTC, SanyaBratashchuk commented on src/style.css
> +  font-family: "Averin";
```suggestion
  font-family: "Avenir";
```
Fix it everywhere

2022-12-27 11:53 UTC, natalia-matash commented on src/style.css
> +  font-family: "Averin";
All have fixed

2022-12-27 11:55 UTC, natalia-matash commented
All have fixed

2022-12-27 16:16 UTC, agniya-i approved these changes

2023-02-01 12:03 UTC, closed without merging