complete
mate-academy/layout_search-bar-airbnb pull request #2643
Opened 2023-01-04 18:38 UTC by VladGraund

https://VladGraund.github.io/layout_search-bar-airbnb/
https://VladGraund.github.io/layout_search-bar-airbnb/report/html_report/

2023-01-05 15:46 UTC, mykhalenych requested changes

2023-01-05 15:46 UTC, mykhalenych commented on src/index.html
> +        <img
better add image in styles
for example
```
.class {
  background: url(./images/Search.svg)
}
```

2023-01-05 15:46 UTC, mykhalenych commented on src/index.html
> +        <img
the same

2023-01-07 09:54 UTC, VladGraund commented on src/index.html
> +        <img
i fixed this

2023-01-09 19:33 UTC, Bohdan-Maksymiuk approved these changes
Good job 👍

2025-02-28 13:59 UTC, closed without merging