Airbnb Search bar
mate-academy/layout_search-bar-airbnb pull request #2658
Opened 2023-01-07 17:39 UTC by Dimoshua

Request description:
- [DEMO LINK](https://Dimoshua.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Dimoshua.github.io/layout_search-bar-airbnb/report/html_report/)

2023-01-07 17:40 UTC, Dimoshua commented
Request description:
- [DEMO LINK](https://Dimoshua.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Dimoshua.github.io/layout_search-bar-airbnb/report/html_report/)

2023-01-08 12:39 UTC, SanyaBratashchuk requested changes
Fix icon size 
![image](https://user-images.githubusercontent.com/97547824/211196501-0276591f-47fb-4952-b07c-dca99caa427b.png)
Remove black outline

2023-01-08 12:39 UTC, SanyaBratashchuk commented on src/style.css
> +}
![image](https://user-images.githubusercontent.com/97547824/211196457-875d28a5-220e-4584-8e6e-1c0ee26a7dc8.png)

2023-01-08 12:39 UTC, SanyaBratashchuk commented on src/style.css
> +  font-family: Avenir-Book, Avenir-Heavy, Avenir, Arial, Helvetica, sans-serif;
```suggestion
  font-family: Avenir, Arial, Helvetica, sans-serif;
```

2023-01-08 19:18 UTC, closed without merging