Develop
mate-academy/layout_search-bar-airbnb pull request #2700
Opened 2023-01-18 15:22 UTC by superzuc

https://superzuc.github.io/layout_search-bar-airbnb/

https://superzuc.github.io/layout_search-bar-airbnb/report/html_report/

2023-01-18 19:55 UTC, polosanya requested changes
Almost perfect!

2023-01-18 19:55 UTC, polosanya commented on src/index.html
> +      >
```suggestion
      <form 
        action="https://mate-academy-form-lesson.herokuapp.com/create-application" 
        method="post"
        data-qa="big"
      >
```

2023-01-18 19:55 UTC, polosanya commented on src/index.html
> +        >
```suggestion
        <input 
          type="search"
          id="searchBar_big"
          name="searchBar"
          placeholder="Try &quot;Los Angeles&quot;"
          data-qa="keypress"
        >
```
Fix all cases.

2023-01-18 19:55 UTC, polosanya commented on src/style.css
> +  position: absolute;
Pay attention to CSS properties order
https://9elements.com/css-rule-order/
You can also set the same box-sizing for all elements using * selector

2023-01-19 18:36 UTC, polosanya requested changes
Links don't work(
Did you make `npm run deploy`?

2023-01-23 17:12 UTC, superzuc commented
I don't know why the link don't work and yes, i've tryed few times on npm run deploy

2023-01-23 20:04 UTC, closed without merging