Develop
mate-academy/layout_search-bar-airbnb pull request #2984
Opened 2023-03-01 22:01 UTC by PavlovaOlena

[DEMO LINK](https://PavlovaOlena.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://PavlovaOlena.github.io/layout_search-bar-airbnb/report/html_report/)

2023-03-02 08:08 UTC, polosanya requested changes
![image](https://user-images.githubusercontent.com/96409563/222367955-894518d5-dc5c-4677-a7f2-ed22c916863f.png)
![image](https://user-images.githubusercontent.com/96409563/222368003-f4b727eb-ee1e-41d4-a3a6-dc8367e9330f.png)

2023-03-02 08:08 UTC, polosanya commented on src/index.html
> +          name="text"
```suggestion
          name="smallSearch" 
```
This name would be more correct

2023-03-02 08:08 UTC, polosanya commented on src/style.css
> +  background: url(images/Search.svg) no-repeat left;
Pay attention to CSS properties order
https://9elements.com/css-rule-order/

2023-03-06 14:24 UTC, witflash approved these changes
Good job 👍

2023-03-06 14:24 UTC, witflash commented on src/index.html
> +          class="input-search input-search-big"
If you use modifier it should be `input-search--big` in BEM methodology.

2023-03-06 14:24 UTC, witflash commented on src/style.css
> +  background: url(images/Search.svg) no-repeat left, linear-gradient(#fff 0%, #f6f6f7 100%);
There is no need to use `background` rule here because you have the same for `input-search:focus` already.

2023-03-06 17:24 UTC, closed without merging