add searchbars
mate-academy/layout_search-bar-airbnb pull request #3014
Opened 2023-03-07 06:23 UTC by Zibi95

[DEMO LINK](https://Zibi95.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://Zibi95.github.io/layout_search-bar-airbnb/report/html_report/)

2023-03-08 11:32 UTC, DorotaLeniecDev requested changes

2023-03-08 11:47 UTC, DorotaLeniecDev requested changes

2023-03-08 11:47 UTC, DorotaLeniecDev commented on src/index.html
> +    <form class="search-form search-form-big" data-qa="big">
According to task description please provide action and method for forms

- You have to put input inside the form for correct data processing. Form should have action and method attributes.

2023-03-08 12:47 UTC, Zibi95 commented
I couldn't add `gap` because puppeter tests doesn't see that property. 
Here is Tip and Hints from other assigment:
> Don't use gap property for indents. It's not supported in tests, use margin instead.

2023-03-08 18:35 UTC, Radoslaw-Czerniawski commented
A few comments from my side: 
- Generally avoid setting margins on both `top` and `bottom`, when positioning elements on top of the other. In set of elements that are stacked, separate them by, for example setting `margin` only for `top`. This way you will always know that next element moves away from the previous according to it's own styles, rather than the previous elements styles cause the next one to change position
- Also top and bottom margins cause your forms margins to collide. They are separated not by combined margins value (which is fine) however it's confusing, if one margin was bigger than the other, bigger value would win. 
- You have to position your cursor in the middle of the form to focus input. This may be kinda confusing for the user that's clicking on what seems to be the input but it does not focus. I think setting on your input `width: 100%` to cover parents height will work.

2023-03-08 20:30 UTC, Radoslaw-Czerniawski requested changes

2023-03-08 20:30 UTC, Radoslaw-Czerniawski commented on src/index.html
> +  <body class="page">
Don't set classes on body element. This is redundant as there is no possibility for you to have more than one `body` element. If you must target body in css do it with tag, however I assume you want to have some type of container for these forms, I suggest wrapping them in a div with a class `wrapper`.

2023-03-09 14:43 UTC, DorotaLeniecDev approved these changes
Thanks for applying all the suggestions. Now task meet all the requirements :)
Sorry I have missed **gap** issue.

2023-03-09 20:19 UTC, Radoslaw-Czerniawski commented
Very good work with margins, input height and overall this whole PR 😄

2023-03-09 20:19 UTC, Radoslaw-Czerniawski approved these changes

2023-03-16 18:05 UTC, closed without merging