two searchbars
mate-academy/layout_search-bar-airbnb pull request #3068
Opened 2023-03-14 13:23 UTC by oleh-stekh

[DEMO LINK](https://oleh-stekh.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://oleh-stekh.github.io/layout_search-bar-airbnb/report/html_report/)

2023-03-14 15:30 UTC, mykhalenych requested changes
looks strange
<img width="347" alt="Screenshot 2023-03-14 at 17 27 34" src="https://user-images.githubusercontent.com/53228259/225051493-bf336241-a461-4ea6-949c-dfd04ee4a924.png">

2023-03-14 15:30 UTC, mykhalenych commented on src/style.css
> +  margin-top: -1px;
why it is -1?

2023-03-14 15:30 UTC, mykhalenych commented on src/style.css
> +  width: 158px;
delete it

2023-03-14 15:30 UTC, mykhalenych commented on src/style.css
> +  margin-top: -1px;
the same

2023-03-14 15:30 UTC, mykhalenych commented on src/style.css
> +  width: 158px;
the same

2023-03-15 08:13 UTC, etojeDenys requested changes
1. try to follow kebab-case or BEM fo naming classes
2. and cover your img and tag in `label`

2023-03-15 13:14 UTC, IvanFesenko approved these changes

2023-12-27 13:20 UTC, closed without merging