solution
mate-academy/layout_search-bar-airbnb pull request #313
Opened 2020-08-28 17:25 UTC by Pavliklaw7

- [DEMO LINK](https://Pavliklaw7.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Pavliklaw7.github.io/layout_search-bar-airbnb/report/html_report/)

2020-08-29 12:11 UTC, solaryasha requested changes
Трошки маленьких зауважень

2020-08-29 12:11 UTC, solaryasha commented on src/index.html
> +        alt="search icon">
```suggestion
      <img
        class="search-icon"
        src="images/Search.svg"
        alt="search icon"
      >
```

2020-08-29 12:11 UTC, solaryasha commented on src/style.css
> +  outline: 0;
```suggestion
  outline: none;
```

2020-08-29 12:11 UTC, solaryasha commented on src/style.css
> +}
```suggestion
*,
*:after,
*::before {
  box-sizing: border-box;
}
```

2020-08-29 12:11 UTC, solaryasha commented on src/style.css
> +  transition: 0.3s;
Задавай transition на конкретну css властивість
Наприклад, transition: box-shadow 0.3s ease-in-out;
`transition: [property] [duration] [timing-function] [delay];`

2020-08-29 12:11 UTC, solaryasha commented on src/style.css
> +  box-sizing: border-box;
Ти це вже вказав вище

2020-08-29 12:11 UTC, solaryasha commented on src/style.css
> +}
Напише це перед `body`

2020-08-31 08:29 UTC, YuriiHoliuk requested changes
ти не виправив коментарі Володі, не роби так

2020-08-31 15:10 UTC, YuriiHoliuk requested changes

2020-08-31 15:10 UTC, YuriiHoliuk commented on src/index.html
> +        >
```suggestion
      <img
        class="search-icon"
        src="images/Search.svg"
        alt="search icon"
      >
```

2020-08-31 15:10 UTC, YuriiHoliuk commented on src/index.html
> +        >
https://mate-academy.github.io/style-guides/htmlcss.html#html-line-wrapping

2020-08-31 15:10 UTC, YuriiHoliuk commented on src/style.css
> +.wrapper.big__bar .search-icon {
apply styles only to a single class
do not use complex seleecctors

2020-08-31 15:10 UTC, YuriiHoliuk commented on src/style.css
> +  height: 70px;
do not hardcode height, use paddings and borders

2020-08-31 15:10 UTC, YuriiHoliuk commented on src/index.html
> +    <div class="wrapper small__bar" data-qa="small">
read BEM documentation if you want to use BEM

2020-08-31 15:35 UTC, Pavliklaw7 commented on src/style.css
> +.wrapper.big__bar .search-icon {
То есть .search-icon нужно заменить на .search-icon__big  и .search-icon__small?

2020-09-02 09:33 UTC, YuriiHoliuk approved these changes
Молодець, розібрався з класами!

2020-10-18 09:17 UTC, closed without merging