add solution search bar airbnb
mate-academy/layout_search-bar-airbnb pull request #3134
Opened 2023-03-29 18:46 UTC by petrushinsky-kirill

- [DEMO LINK](https://petrushinsky-kirill.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://petrushinsky-kirill.github.io/layout_search-bar-airbnb/report/html_report/)

2023-03-30 07:27 UTC, polosanya requested changes
Good job! Let's improve your solution a bit)
![image](https://user-images.githubusercontent.com/96409563/228759084-e386f914-ca2b-47ad-87ab-58e17de2df1d.png)
![image](https://user-images.githubusercontent.com/96409563/228759015-9832e9fc-9787-4d2a-8770-bfd5dbf8633c.png)
Pay attention to styles on focus
![image](https://user-images.githubusercontent.com/96409563/228759236-85c8f7f5-91c3-4cdf-8e38-91faca7e3bd1.png)
![image](https://user-images.githubusercontent.com/96409563/228759328-5622fb7c-8c2c-46ec-846b-0f8aa971c2c8.png)

2023-03-30 07:27 UTC, polosanya commented on src/index.html
> +          size="100%">
```suggestion
        <input
          class="input__large"
          data-qa="keypress"
          type="text" 
          id="largeInput"
          placeholder="Try &quot;Los Angeles&quot;"
        >
```
![image](https://user-images.githubusercontent.com/96409563/228759754-8e5ccd2a-7cf5-4cdd-879c-97b1102918ef.png)
Better set the size using CSS styles and not size attribute

2023-03-30 07:27 UTC, polosanya commented on src/index.html
> +        <div class="search-icon__large"></div>
I think it's better to use img tag here

2023-03-30 07:27 UTC, polosanya commented on src/style.css
> +input {
![image](https://user-images.githubusercontent.com/96409563/228760635-ba70d7e2-d80b-4a29-ba25-5cd7a0e25183.png)

2023-03-30 07:27 UTC, polosanya commented on src/style.css
> +  width: 11.01px;
You are certainly doing something wrong if you need to use float values

2023-03-30 17:01 UTC, agniya-i requested changes
Please fix all previous comments, 

If you have any questions ask in fe_chat

2023-03-31 06:47 UTC, polosanya requested changes
Almost done!
Make sure that you set the correct font and font styles on focus. Now it doesn't look like Avenir
![image](https://user-images.githubusercontent.com/96409563/229042434-279c97d1-0db0-46da-80c7-7a674ae0cd1c.png)
![image](https://user-images.githubusercontent.com/96409563/229042490-4461f762-39e5-4784-bdee-ed7283656633.png)

2023-03-31 06:47 UTC, polosanya commented on src/index.html
> +      >
```suggestion
    <form
      action="https://mate-academy-form-lesson.herokuapp.com/create-application"
      data-qa="big"
      method="GET"
    >
```

2023-03-31 06:47 UTC, polosanya commented on src/index.html
> +        >
```suggestion
      <label for="largeInput" class="large__bar">
```
You don't really need `for` attribute, as you wrap input into the label

2023-03-31 06:47 UTC, polosanya commented on src/index.html
> +          >
```suggestion
        <img
          src="images/Search.svg"
          alt="icon"
          class="large__icon"
        >
        <input
          class="input__large"
          data-qa="keypress"
          type="text"
          id="largeInput"
          placeholder="Try &quot;Los Angeles&quot;"
        >
```
Closing tag should be under the opening. Please fix all cases
![image](https://user-images.githubusercontent.com/96409563/229042994-565b4076-0a3f-4695-938d-ab122ec84a8a.png)

2023-03-31 06:47 UTC, polosanya commented on src/style.css
> +  border: 1px solid #e1e7ed;
But you have the same border for the default state. Do you need to change it on focus?

2023-03-31 18:37 UTC, agniya-i requested changes

2023-03-31 18:37 UTC, agniya-i commented on src/style.css
> +.input__small {
Good job) Let's improve a little bit)

You have a lot of similar styles for both inputs, use styles for big input as base, and then override necessary properties for small input

[CHECKLIST](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md ) p2

2023-04-01 17:25 UTC, agniya-i approved these changes
🔥

2025-02-14 14:24 UTC, closed without merging