layout_search-bar-airbnb
mate-academy/layout_search-bar-airbnb pull request #3167
Opened 2023-04-04 13:53 UTC by nazarg74

2023-04-05 06:23 UTC, polosanya requested changes
Almost done!
Please don't forget to add demo links to your PR description
![image](https://user-images.githubusercontent.com/96409563/229996953-43bf826e-87fb-4d0a-b891-3104fad883a3.png)
![image](https://user-images.githubusercontent.com/96409563/229997898-0a008a34-1a07-48be-87b1-36b086fce4a9.png)

![image](https://user-images.githubusercontent.com/96409563/229997868-09aeea86-c904-4020-ab8e-2e0c1b730270.png)

2023-04-05 06:23 UTC, polosanya commented on src/index.html
> +        >
Fix all cases
```suggestion
        <input 
          class="input"
          type="text"
          data-qa="keypress"
          placeholder="Try &quot;Los Angeles&quot;"
        >
```
![image](https://user-images.githubusercontent.com/96409563/229997088-fb8c81ab-0cb2-4119-8944-7ce7b5fffc77.png)

2023-04-05 06:23 UTC, polosanya commented on src/style.css
> +input::placeholder {
![image](https://user-images.githubusercontent.com/96409563/229997703-a58b91d1-e131-485c-baf6-cadbd1288ca1.png)

2023-04-25 13:16 UTC, nazarg74 commented
https://nazarg74.github.io/layout_search-bar-airbnb/
https://nazarg74.github.io/layout_search-bar-airbnb/report/html_report/

2023-06-26 15:45 UTC, nazarg74 commented
The task was already completed before the topic was updated on the site)

2026-04-15 19:43 UTC, closed without merging