Add task changes
mate-academy/layout_search-bar-airbnb pull request #3181
Opened 2023-04-06 08:52 UTC by FIREDAN99

2023-04-06 10:38 UTC, VitaliyBondarenko1982 requested changes
also remove outline for inputs
```
outline: none
```

![Screenshot from 2023-04-06 13-20-40](https://user-images.githubusercontent.com/33029864/230353571-9fd0a9c9-39ce-4a67-8b14-032a7db00be9.png)

2023-04-06 10:38 UTC, VitaliyBondarenko1982 commented on src/style.css
> +[data-qa="big"] {
get used to style all elements using classes
and check this point from [checklist](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md)
![Screenshot from 2023-04-06 13-23-02](https://user-images.githubusercontent.com/33029864/230351261-958fb110-1033-4c49-97dc-8182cb805c81.png)

2023-04-06 10:38 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  font-weight: 400;
```suggestion
  padding-left: 62px;
```
resundant - 400 is default font-weight

2023-04-06 10:38 UTC, VitaliyBondarenko1982 commented on src/style.css
> +}
check styles and remove repeatable, and which not necessary to set again ( small input, hover, focus states)
for example make class search, and search-small for small form, where reset only classes, which different from big form

2023-04-06 10:38 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  box-sizing: border-box;
move to * selector
```
* {
  box-sizing: border-box;
}

2023-04-06 10:38 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  box-sizing: border-box;
same. move to * selector

* {
  box-sizing: border-box;
}

2023-04-09 17:29 UTC, FIREDAN99 commented
add task changes2

2023-04-09 17:32 UTC, closed without merging