create search-bar-airbnb
mate-academy/layout_search-bar-airbnb pull request #3221
Opened 2023-04-11 00:10 UTC by olhry

https://olhry.github.io/layout_search-bar-airbnb/
https://olhry.github.io/layout_search-bar-airbnb/report/html_report/

2023-04-11 07:41 UTC, polosanya requested changes
Almost done! 
The font on focus doesn't match the design
![image](https://user-images.githubusercontent.com/96409563/231090579-7bcf22be-41ca-4e80-a862-39095650658b.png)
![image](https://user-images.githubusercontent.com/96409563/231090612-b10e3658-b0c3-488d-b1a2-3c5e498c4918.png)

2023-04-11 07:41 UTC, polosanya commented on src/style.css
> +form[data-qa="big"] {
![image](https://user-images.githubusercontent.com/96409563/231090297-fdea7199-3d41-4ae6-85a5-d6c9627e0c3f.png)

2023-04-11 21:57 UTC, olhry commented on src/index.html
>    </body>
changed

2023-04-12 09:34 UTC, ivadimko commented on src/style.css
> +  font-family: Avenir;
Consider using a more descriptive font-style value like 'bold' instead of 'heavy'.

2023-04-12 09:34 UTC, ivadimko commented on src/style.css
> +form[data-qa="small"]:focus {
This rule is targeting the whole form instead of the input itself. Use .smallSearch:focus to target the input directly.

2023-04-12 09:34 UTC, ivadimko commented on src/style.css
> +  font-style: book;
Consider using a more descriptive font-style value like 'normal' instead of 'book'.

2023-04-12 09:34 UTC, ivadimko commented on src/style.css
> +form[data-qa="big"]:focus {
This rule is targeting the whole form instead of the input itself. Also, use class for styling

2023-04-27 06:20 UTC, polosanya requested changes
Almost perfect! Let's try to pass all tests.
The font family doesn't match the design. It should be Avenir instead of Arial
![image](https://user-images.githubusercontent.com/96409563/234775720-c5b1c48c-1847-4e5a-a827-0f95f9539a56.png)
Feel free to ask for help in fe_chat if you have any difficulties 🙂

2023-04-27 06:20 UTC, polosanya commented on src/style.css
> +  font-weight: 300;
Set the font family for body and inherit it where needed

2023-04-27 06:20 UTC, polosanya commented on src/style.css
> +  font-style: normal;
I guess it should be bold instead of normal

2023-05-10 11:45 UTC, ivadimko reviewed
.

2023-09-03 07:41 UTC, OleziO requested changes
Remove the limit on the number of characters in the input so that its entire area is clickable.
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/56752562/258c3dbe-b33c-4899-b94b-7ebab1a01190)

2023-09-03 07:41 UTC, OleziO commented on src/index.html
> +      >
Add empty line.

2023-09-03 07:41 UTC, OleziO commented on src/index.html
> +    </form>
Add empty line.

2023-09-03 07:41 UTC, OleziO commented on src/style.css
> +  box-sizing: border-box;
Better is to move it in * selector and remove from all other places.

2023-09-03 07:41 UTC, OleziO commented on src/style.css
> +  box-shadow: 0 1px 8px 0 rgba(61, 78, 97, 0.1);
Use HEX instead of RGBA

2023-09-04 07:35 UTC, ivadimko reviewed
.

2023-09-04 12:46 UTC, IvanFesenko approved these changes
well done

2024-04-05 21:26 UTC, closed without merging