search_bar
mate-academy/layout_search-bar-airbnb pull request #3244
Opened 2023-04-17 12:36 UTC by Yaroslav220890

- [DEMO LINK](https://Yaroslav220890.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Yaroslav220890.github.io/layout_search-bar-airbnb/report/html_report/)

2023-04-17 12:43 UTC, IvanFesenko requested changes

2023-04-17 12:43 UTC, IvanFesenko commented on src/index.html
> +            >
Pay attention on indents
```suggestion
          <input class="input_small"
            name="s"
            placeholder="Try &#34Los Angeles&#34"
            type="search"
            data-qa="small"
          >
```

2023-04-17 12:43 UTC, IvanFesenko commented on src/style.css
> +}
Why class name is radius? Are you making a circle?

2023-04-17 12:43 UTC, IvanFesenko commented on src/style.css
> +}
Do not repeat your self
![2023-04-17_15h39_09](https://user-images.githubusercontent.com/61904995/232486802-130bbd32-092d-47bc-b9d3-7a3084e38b84.png)

2023-04-17 12:43 UTC, IvanFesenko commented on src/style.css
> +  font-family: "Avenir-Heavy", sans-serif;
Move `font-family` into html selector. For input use inherit value
```suggestion
  font-family: inherit;
```

2023-04-17 12:43 UTC, IvanFesenko commented on src/style.css
> +}
Same as above, do not repeat your self

2023-04-17 12:43 UTC, IvanFesenko commented on src/index.html
> +          </button>
My assumption search icon should be done with pseudo ::before instead of button

2023-04-17 15:17 UTC, Yaroslav220890 commented
Оновив

2023-04-17 17:29 UTC, qoa11a requested changes
Please, read the checklist and follow the rules that are mentioned in it carefully. Also, please, don't ignore mentors' suggestions.
If you have issues with something or you can't understand what the comment means - please, ask in the fe_chat in Slack.

2023-04-17 17:29 UTC, qoa11a commented on src/index.html
> +        >
```suggestion
        <form 
          class="form"
          autofocus
          action="value"
          method="get"
          data-qa="big"
        >
```
Please, fix the code style everywhere. In this situation, you should apply this rule. But please, read the checklist carefully and refactor your code.
https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md
![image](https://user-images.githubusercontent.com/102293862/232562937-3bf14b97-22bc-41e6-8224-9e21b08135b8.png)

2023-04-17 17:29 UTC, qoa11a commented on src/index.html
> +      <div class="radius radius_small">
Why the class name is `radius`? You have not fixed it. Please, fix all the comments that mentors left.

2023-04-17 17:29 UTC, qoa11a commented on src/index.html
> +          </button>
It should be made with the `::before` pseudo-element. Please, pay attention to the comments that mentors have left.

2023-04-17 17:32 UTC, Yaroslav220890 commented on src/index.html
> +      <div class="radius radius_small">
У рідмі не написано як називати класи, я поставив радіус тому що цей блок задає радіус

2023-04-17 17:55 UTC, Yaroslav220890 commented on src/index.html
> +        >
Я помітив, клас перенести на наступну строку?

2023-04-18 06:30 UTC, Yaroslav220890 commented on src/index.html
> +          </button>
а чому тоді це не прописано в readme? Там взагалі нічого не сказано про те що треба робити before?

2023-04-18 10:19 UTC, anstsot requested changes
Great job, but the tests failed. can you check, please? or write in the chat and mentors will try to help you

2023-04-18 10:19 UTC, anstsot commented on src/index.html
> +      <div class="search_bar search_bar_small">
```suggestion
      </div>
      
      <div class="search_bar search_bar_small">
```

2023-04-18 10:21 UTC, Yaroslav220890 commented
Я знаю шо тест не проходе і скидав посилання ще декілька днів тому

2023-04-18 10:24 UTC, Yaroslav220890 commented on src/index.html
> +      <div class="search_bar search_bar_small">
Чому кожен ментор бачить стиль коду по своєму і на основі цього відміняє задачу? Ви вже 3-й хто пише свої правила коду або не помічає і так по 10 раз одне й те саме

2023-04-18 10:42 UTC, IvanFesenko approved these changes
Pay attention on my comment.

2023-04-18 10:42 UTC, IvanFesenko commented on src/style.css
> +  font-style: #3d4e61;
this wont work
```suggestion
```

2023-04-21 09:41 UTC, closed without merging