solution
mate-academy/layout_search-bar-airbnb pull request #328
Opened 2020-11-03 18:58 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://Layrovell.github.io/layout_search-bar-airbnb/report/html_report/)

2020-11-04 08:32 UTC, Denchepornyuk requested changes

2020-11-04 08:32 UTC, Denchepornyuk commented on src/index.html
> +    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta
        name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```

2020-11-04 08:32 UTC, Denchepornyuk commented on src/index.html
> +      alt="search-icon">
якщо три і більше атрибутів в тегу то кожен атрибут потрібно писати з нової лінії

2020-11-04 08:32 UTC, Denchepornyuk commented on src/style.css
> +}
```suggestion
  src: url("./fonts/Avenir-Book.ttf");
}
```

2020-11-05 20:21 UTC, Layrovell commented on src/index.html
> +      alt="search-icon">
done

2020-11-05 20:21 UTC, Layrovell commented on src/index.html
> +    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
done

2020-11-05 20:21 UTC, Layrovell commented on src/style.css
> +}
done

2020-11-06 09:15 UTC, Denchepornyuk requested changes

2020-11-06 09:15 UTC, Denchepornyuk commented on src/index.html
> +      data-qa="keypress">
для кожного тега в якого три і більше атррибутів потрібно пофіксити переноси

2020-11-06 12:56 UTC, Denchepornyuk approved these changes

2020-11-06 12:56 UTC, Denchepornyuk commented on src/index.html
> +      >
а для цих тегів атрибути не вирівняла(

2023-04-05 21:27 UTC, closed without merging