Develop
mate-academy/layout_search-bar-airbnb pull request #3345
Opened 2023-07-03 16:30 UTC by Igor-Pysak

- [DEMO LINK](https://Igor-Pysak.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Igor-Pysak.github.io/layout_search-bar-airbnb/report/html_report/)

2023-07-03 18:02 UTC, Viktor-Kost requested changes
Great job!
Some moments can be improved

2023-07-03 18:02 UTC, Viktor-Kost commented on src/style.css
> +  padding: 25px 0 0 26px;
use top/left rules to position absoluted icon
```suggestion
```

2023-07-03 18:02 UTC, Viktor-Kost commented on src/style.css
> +  padding: 15px 0 0 13px;
the same with top/left

2023-07-04 09:12 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2024-10-21 09:56 UTC, closed without merging