add task solution
mate-academy/layout_search-bar-airbnb pull request #3381
Opened 2023-07-11 13:02 UTC by mishakoshilka

- [DEMO LINK](https://mishakoshilka.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://mishakoshilka.github.io/layout_search-bar-airbnb/report/html_report/)

2023-07-11 15:17 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's fix the problem with tests. You need to check styles for `font-family`

2023-07-11 15:17 UTC, volodymyr-soltys97 commented on src/index.html
> +    data-qa="big">
You need to check and fix it everywhere
<img width="1054" alt="image" src="https://github.com/mate-academy/layout_search-bar-airbnb/assets/64750958/b0d10fe3-4ae7-4d37-a30a-cac31ff2a2d9">

2023-07-11 17:49 UTC, Viktor-Kost requested changes

2023-07-11 17:49 UTC, Viktor-Kost commented on src/index.html
> +
an extra empty line 
```suggestion
```

2023-07-11 17:49 UTC, Viktor-Kost commented on src/index.html
> +
an extra empty line
```suggestion
```

2023-07-11 17:49 UTC, Viktor-Kost commented on src/style.css
> +/* #region big */
no needs to add such comments
```suggestion
```

2023-07-11 17:49 UTC, Viktor-Kost commented on src/style.css
> +  line-height: normal;
use numeric value

Example:
line-height: 16px;

2023-07-12 08:07 UTC, volodymyr-soltys97 approved these changes

2023-07-12 08:07 UTC, volodymyr-soltys97 commented on src/style.css
> +  font-style: normal;
No need to write `normal`. This is default value
```suggestion
```

2024-12-27 09:02 UTC, closed without merging