add task solution
mate-academy/layout_search-bar-airbnb pull request #3466
Opened 2023-07-31 20:37 UTC by ApheliosGM

[DEMO LINK](https://ApheliosGM.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://ApheliosGM.github.io/layout_search-bar-airbnb/report/html_report/)

2023-08-01 08:43 UTC, denys-danyliuk requested changes

2023-08-01 08:43 UTC, denys-danyliuk commented on src/index.html
> +          name="big-input"
6'th point in checklist

2023-08-10 08:51 UTC, denys-danyliuk requested changes

2023-08-10 08:51 UTC, denys-danyliuk commented on src/style.css
> +}
2'nd point in checklist

2023-08-15 14:46 UTC, mykhalenych approved these changes

2023-08-15 14:46 UTC, mykhalenych commented on src/style.css
> +  font-family: "Avenir", Arial, Calibri, sans-serif;
you already added styles in html selector

2025-08-08 14:43 UTC, closed without merging