add task solution
mate-academy/layout_search-bar-airbnb pull request #3501
Opened 2023-08-09 16:37 UTC by vbevziuk

- [DEMO LINK](https://vbevziuk.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://vbevziuk.github.io/layout_search-bar-airbnb/report/html_report/)

2023-08-10 08:28 UTC, anastasiia-tilikina requested changes
GJ)

let's add some fixes. check my comments.
also, placeholders' styles don't change on focus. 

![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/108538921/ecf56f2e-a8b7-46d9-a497-a153dd2f0cf1)

These styles for focus in Figma show how input text should look, not placeholder.

2023-08-10 08:28 UTC, anastasiia-tilikina commented on src/style.css
> +  transform: translate(0, -50%);
```suggestion
  transform: translateY(-50%);
```

2023-08-10 08:28 UTC, anastasiia-tilikina commented on src/index.html
> +      <label class="search-form__icon"></label>
add `for` attribute to make label clickable

2023-08-10 08:28 UTC, anastasiia-tilikina commented on src/style.css
> +  font-weight: bold;
Use the same units of measurement for `font-weight`, be consictent

2023-08-10 08:28 UTC, anastasiia-tilikina commented on src/style.css
> +  height: 70px;
you don't need to hardcode height. use paddings to adjust height instead.

2023-08-10 08:28 UTC, anastasiia-tilikina commented on src/style.css
> +  font-family: Avenir, sans-serif;
assign default text styles on entire document and just override them where you need.

2023-08-11 07:10 UTC, etojeDenys approved these changes
good job

2024-01-22 10:35 UTC, closed without merging