search bar added
mate-academy/layout_search-bar-airbnb pull request #3661
Opened 2023-10-01 06:21 UTC by AlNeon

- [DEMO LINK](https://AlNeon.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://AlNeon.github.io/layout_search-bar-airbnb/report/html_report/)

2023-10-01 14:18 UTC, VitaliyBondarenko1982 requested changes
Good job.
Need some improvements.

2023-10-01 14:18 UTC, VitaliyBondarenko1982 commented on src/index.html
> +      >
each input shuould have a label. 
wrap input in label.

2023-10-01 14:18 UTC, VitaliyBondarenko1982 commented on src/index.html
> +        class="search__form__input big__input"
```suggestion
        class="search__form__input"
```
pay attention on this point from [checklist](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/checklist.md)
![Screenshot from 2023-10-01 17-16-12](https://github.com/mate-academy/layout_search-bar-airbnb/assets/33029864/12ecacf9-1b34-4e06-a2f3-28484d95dde6)

2023-10-02 11:30 UTC, VitaliyBodnar requested changes

2023-10-02 11:30 UTC, VitaliyBodnar commented on src/style.css
> +  box-shadow: 0 1px 8px rgba(61, 78, 97, 0.1);
61, 78, 97 duplicated color, so make sense to move it to the variables
check other places

2023-10-03 14:53 UTC, loralevitska approved these changes
Well done)

2024-05-21 14:47 UTC, closed without merging