add search form
mate-academy/layout_search-bar-airbnb pull request #3671
Opened 2023-10-06 13:36 UTC by RuslanSkl

- [DEMO LINK](https://RuslanSkl.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://RuslanSkl.github.io/layout_search-bar-airbnb/report/html_report/)

2023-10-06 14:15 UTC, RuslanSkl commented
Interesting... but i pass all tests
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/95960574/7dcb2ecd-fbd7-4db7-bd4c-882a3bb73f72)

2023-10-06 14:30 UTC, loralevitska requested changes
Almost done) Let's improve

2023-10-06 14:30 UTC, loralevitska commented on src/index.html
> +        class="search-form__label search-form__label_big">
```suggestion
      <label
        for="big-search"
        class="search-form__label search-form__label_big"
      >
```

2023-10-06 14:30 UTC, loralevitska commented on src/index.html
> +        class="search-form__label search-form__label_small">
```suggestion
      <label
        for="small-search"
        class="search-form__label search-form__label_small"
      >
```

2023-10-06 14:30 UTC, loralevitska commented on src/style.css
> +  padding: 0;
Only `box-sizing` allow for `*` selector. Please move `padding` property for `body` tag
```suggestion
```

2023-10-06 14:30 UTC, loralevitska commented on src/style.css
> +  font-style: normal;
Remove redundant default value of property
```suggestion
```

2023-10-06 14:30 UTC, loralevitska commented on src/style.css
> +  background-size: contain;
`background` shorthand property can be used

2023-10-06 14:30 UTC, loralevitska commented on src/style.css
> +  background-size: contain;
Combine repeatable code into common class

2023-10-06 14:30 UTC, loralevitska commented on src/style.css
> +  font-family: "Avenir-Book", sans-serif;
Move to `html` selector and here inherit this property

2023-10-09 12:51 UTC, anastasiiavorobiova approved these changes
Great work!

2025-01-20 09:18 UTC, closed without merging