add task solution
mate-academy/layout_search-bar-airbnb pull request #3815
Opened 2023-11-27 18:17 UTC by arthur10031198

- [DEMO LINK](https://arthur10031198.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://arthur10031198.github.io/layout_search-bar-airbnb/report/html_report/)

2023-11-27 19:26 UTC, TarasHoliuk requested changes
GJ :+1: 
Let's add some improvements/fixes

2023-11-28 11:15 UTC, anastasiiavorobiova requested changes
Could you read the comments from the previous review carefully and fix them? Also, there is a default outline here 
<img width="322" alt="Screenshot 2023-11-28 at 13 12 44" src="https://github.com/mate-academy/layout_search-bar-airbnb/assets/135232001/093416ee-8d95-45b5-a8f7-756283cdb93f">

2023-11-28 12:52 UTC, anastasiiavorobiova requested changes
Feel free to ask for help in the chat to fix issues here

2023-11-28 13:02 UTC, arthur10031198 commented
you have changes in the code?

2023-11-28 15:27 UTC, VitaliyBodnar commented on src/index.html
> +    <form class="search-panel-2" data-qa="small" >
Not fixed

2023-11-28 15:27 UTC, VitaliyBodnar commented on src/style.css
> +  src: url(fonts/Avenir-Heavy.ttf);
Not fixed

2023-11-28 15:29 UTC, VitaliyBodnar commented on src/style.css
> +  box-sizing: border-box;
It's better practice to put the box-sizing to this block `*{}` as it this be applied in everywhere

2023-11-28 15:29 UTC, VitaliyBodnar commented on src/style.css
> +  font-family: "Avenir", sans-serif;
Font-family is duplicated, so please move it to tag body

2023-11-28 15:30 UTC, VitaliyBodnar commented on src/style.css
> +
Redundant spaces
Check other places 
```suggestion
```

2023-11-29 12:01 UTC, VitaliyBodnar requested changes
.

2023-11-29 12:58 UTC, closed without merging