add search bars
mate-academy/layout_search-bar-airbnb pull request #3828
Opened 2023-11-29 19:11 UTC by manch0ffline

- [DEMO LINK](https://manch0ffline.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://manch0ffline.github.io/layout_search-bar-airbnb/report/html_report/)

2023-11-29 19:42 UTC, loralevitska requested changes
Almost perfect) Let's improve

2023-11-29 19:42 UTC, loralevitska commented on src/index.html
> +        <div class="img img--small"></div>
Try to use `img` tag for this

2023-11-29 19:42 UTC, loralevitska commented on src/index.html
> +        <div class="img img--big"></div>
Try to use img tag for this

2023-11-30 20:01 UTC, loralevitska requested changes
Please redeploy your solution for review 
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/70009205/73877d63-0672-44a4-8d65-06a027367118)
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

2023-12-02 17:27 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2023-12-02 17:27 UTC, volodymyr-soltys97 commented on src/style.css
> +  font-weight: 400;
Default value, so you can just remove it
```suggestion
```

2023-12-03 12:23 UTC, closed without merging