add task solution
mate-academy/layout_search-bar-airbnb pull request #3850
Opened 2023-12-06 20:07 UTC by timossha

- [DEMO LINK](https://timossha.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://timossha.github.io/layout_search-bar-airbnb/report/html_report/)

2023-12-07 07:34 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-12-07 07:34 UTC, volodymyr-soltys97 commented on src/index.html
> +      <div data-qa="big" class="bars bar__big">
This div is redundant, use a label tag instead of div

2023-12-07 07:34 UTC, volodymyr-soltys97 commented on src/index.html
> +        placeholder="Try “Los Angeles”" >
Need to fix it everywhere
```suggestion
        <input
          class="bar__inputs bar__input__big"
          type="text"
          placeholder="Try “Los Angeles”"
        >
```

2023-12-07 07:34 UTC, volodymyr-soltys97 commented on src/style.css
> +  box-sizing:border-box;
You can move box sizing to the * selector
```suggestion
  box-sizing: border-box;
```

2023-12-07 07:34 UTC, volodymyr-soltys97 commented on src/style.css
> +  outline:none;
```suggestion
  outline: none;
```

2023-12-07 20:44 UTC, closed without merging

2023-12-10 17:49 UTC, timossha commented
@volodymyr-soltys97  привіт мені ментор написав щоб я тегнув якщо не перевірять ) а я не знаю як він підписаний на гітхабі