One
mate-academy/layout_search-bar-airbnb pull request #3859
Opened 2023-12-08 23:47 UTC by oralag2

- [DEMO LINK](https://oralag2.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://oralag2.github.io/layout_search-bar-airbnb/report/html_report/)

❗️ Copy this `Checklist` to the `Pull Request` description after links, and put `- [x]` before each point after you checked it.

- [ ] Icon implemented using background-image CSS property
- [ ] Inputs are written inside of 'form' tag with correctly passed attributes
- [ ] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [ ] Code follows all the [Code Style Rules ❗️](./checklist.md)

2023-12-09 07:26 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
The search field should span the entire width
<img width="1021" alt="image" src="https://github.com/mate-academy/layout_search-bar-airbnb/assets/64750958/dd0f169a-6b1d-4d50-b2e4-15973c0d6841">

2023-12-09 07:26 UTC, volodymyr-soltys97 commented on src/index.html
> +    >
Need to fix code style everywhere
```suggestion
    <form
      action="https://www.google.com/search"
      method="get"
      class="container container__big"
      data-qa="big"
    >
```

2023-12-09 07:26 UTC, volodymyr-soltys97 commented on src/index.html
> +                     search-button--big">
Redundant
```suggestion
```

2023-12-09 07:26 UTC, volodymyr-soltys97 commented on src/style.css
> +  font-weight: 400;
Default value, so you can just remove it
```suggestion
```

2023-12-14 21:48 UTC, oralag2 commented
Help me I dont understand

2023-12-14 22:00 UTC, closed without merging