layout-search-bar
mate-academy/layout_search-bar-airbnb pull request #3965
Opened 2024-01-13 12:41 UTC by svyatoslavPy

2024-01-13 13:04 UTC, l4st1m0za requested changes
Grerat job! One thing to change is your font weight. In the tests it's clear that you have some difference with the needed result!

2024-01-13 13:04 UTC, l4st1m0za commented on src/index.html
> +        placeholder="Try “Los Angeles”">
```suggestion
        <input
          class="search-bar__input
          search-bar__input--size--large"
          type="text"
          data-qa="big"
          placeholder="Try “Los Angeles”"
        >
```

Use this styling for all the cases.

2024-01-15 12:21 UTC, anastasiiavorobiova approved these changes
Great work!

2024-01-15 12:21 UTC, anastasiiavorobiova commented on src/index.html
> +      method="post">
```suggestion
    <form
      class="search-bar__form"
      data-qa="keypress"
      method="post"
    >
```

2024-01-15 12:21 UTC, anastasiiavorobiova commented on src/index.html
> +          placeholder="Try “Los Angeles”">
```suggestion
          placeholder="Try “Los Angeles”"
        >
```

2024-01-15 12:21 UTC, anastasiiavorobiova commented on src/index.html
> +          placeholder="Try “Los Angeles”">
```suggestion
          placeholder="Try “Los Angeles”"
        >
```

2024-09-28 18:29 UTC, closed without merging