S B ready
mate-academy/layout_search-bar-airbnb pull request #403
Opened 2021-01-15 18:58 UTC by Frant22

- [DEMO LINK](https://Frant22.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Frant22.github.io/layout_search-bar-airbnb/report/html_report/)

2021-01-16 15:28 UTC, solaryasha requested changes

2021-01-16 15:28 UTC, solaryasha commented on src/index.html
> +    <form data-qa="big">
Додай атрибут `action` `method` `name`

2021-01-16 15:28 UTC, solaryasha commented on src/index.html
> +                 placeholder="Try &#34;Los Angeles&#34;">
Неправильне форматування
```suggestion
          <input 
            id="big"
            class="bigest"
            type="search"
            data-qa="keypress"
            placeholder="Try &#34;Los Angeles&#34;"
          >
```

2021-01-16 15:28 UTC, solaryasha commented on src/index.html
> +          <input id="small"
Тут також поправ форматування

2021-01-16 15:28 UTC, solaryasha commented on src/style.css
> +  box-shadow: 0 1px 8px rgba(61, 78, 97, 0.1);
Зроби відступи між різними групами CSS правил. Так твій код буде легше читати і підтримувати.
```suggestion
  height: 70px;
  width: 100%;
  padding-left: 62px;
  
  font-family: "Avenir-Book", Arial, sans-serif;
  font-size: 16px;
  
  border: 1px solid #e1e7ed;
  border-radius: 4px;
  box-shadow: 0 1px 8px rgba(61, 78, 97, 0.1);
```

2021-01-16 15:28 UTC, solaryasha commented on src/style.css
> +  font-family: "Avenir-Book", Arial, sans-serif;
Avenir Heavy для інпутів і Avenir Book для placeholder-a

2021-01-18 09:05 UTC, Vladimir-Beliy approved these changes

2021-01-18 09:05 UTC, Vladimir-Beliy commented on src/style.css
> +}
хочется создать один класс search-bar, место двух, и дополнительные классы для маленького search-bar

2024-09-28 09:28 UTC, closed without merging