add task solution
mate-academy/layout_search-bar-airbnb pull request #4065
Opened 2024-02-13 13:38 UTC by VladaProskura

- [DEMO LINK](https://VladaProskura.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://VladaProskura.github.io/layout_search-bar-airbnb/report/html_report/)

2024-02-13 13:43 UTC, anastasiiavorobiova requested changes
Consider deploying your solution

2024-02-13 15:00 UTC, VladaProskura commented
> Consider deploying your solution

Please, explain in more detail what needs to be done?

2024-02-14 07:37 UTC, OleziO requested changes
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/56752562/bb0d15ac-fb39-4de6-9c79-7a638ab7f985)
Fix demo link.

2024-02-14 07:37 UTC, OleziO commented on src/style.css
> +
```suggestion
```

2024-02-14 07:37 UTC, OleziO commented on src/style.css
> +  border: 1px solid #E1E7ED;
Move all repeatable colors to the CSS variables.

[More info](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2024-02-15 08:34 UTC, OleziO requested changes

2024-02-15 08:34 UTC, OleziO commented on src/style.css
>  /* add styles here */
Remove all comments from the code.

2024-02-20 16:34 UTC, etojeDenys requested changes
still, your links don't work, try to fix that

2024-03-17 08:38 UTC, SanyaBratashchuk requested changes
1. Placeholders have different font-weight on focus 
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/97547824/12649b3c-3b8a-45c1-b9ac-5b294511b180)
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/97547824/dcf195a9-7a18-4427-b071-15fe791a0621)

2024-03-22 23:45 UTC, closed without merging