add solution
mate-academy/layout_search-bar-airbnb pull request #4080
Opened 2024-02-19 17:15 UTC by hardixxxxx

- [DEMO LINK](https://hardixxxxx.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://hardixxxxx.github.io/layout_search-bar-airbnb/report/html_report/)

- [x] Icon implemented using background-image CSS property
- [x] Inputs are written inside of 'form' tag with correctly passed attributes
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-02-19 17:46 UTC, Esceype requested changes
GJ!
Read the following comments:

2024-02-19 17:46 UTC, Esceype commented on src/index.html
> +        placeholder="Try “Los Angeles”"
```suggestion
        placeholder="Try &quot;Los Angeles&quot;"
```
Use ` &quot;` instead

2024-02-19 17:46 UTC, Esceype commented on src/style.css
> +  background-size: 11px;
```suggestion
  background-size: 11px 11px;
```

2024-02-20 07:08 UTC, IvanFesenko requested changes
Check my comments

2024-02-20 07:08 UTC, IvanFesenko commented on src/style.css
> +  background-size: 19px 19px;
![2024-02-20_09h06_02](https://github.com/mate-academy/layout_search-bar-airbnb/assets/61904995/0b1ce9fe-c012-4fde-94b5-81f773bd798f)

2024-02-20 07:08 UTC, IvanFesenko commented on src/style.css
> +  box-sizing: border-box;
Move `box-sizing: border-box;` into `*` selector

2024-02-20 07:08 UTC, IvanFesenko commented on src/style.css
> +  font-size: 14px;
Do not repeat your self. Use class .search-bar that will have all properties, and only usign modifiers - change required properties

2024-02-20 18:40 UTC, maxim2310 requested changes
Good work, but lets make some improvement 

1. on focus fonts style are different 
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/96265844/ae4441cb-6148-4f5a-8743-fe517b4ce987)
2. also need to fix icon position 
![image](https://github.com/mate-academy/layout_search-bar-airbnb/assets/96265844/31264930-37c5-4c04-9382-7f56de8e65e8)

2024-02-20 18:40 UTC, maxim2310 commented on src/index.html
> +    <form class="mall-search-bar" data-qa="small">
```suggestion
    <form class="small-search-bar" data-qa="small">
```

2024-02-20 18:40 UTC, maxim2310 commented on src/style.css
> +  height: 70px;
```suggestion
```

2024-02-20 18:40 UTC, maxim2310 commented on src/style.css
> +  height: 42px;
```suggestion
```

2024-02-20 19:24 UTC, hardixxxxx commented
> Good work, but lets make some improvement
> 
>     1. on focus fonts style are different
>        ![image](https://private-user-images.githubusercontent.com/96265844/306379983-ae4441cb-6148-4f5a-8743-fe517b4ce987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTY4NzksIm5iZiI6MTcwODQ1NjU3OSwicGF0aCI6Ii85NjI2NTg0NC8zMDYzNzk5ODMtYWU0NDQxY2ItNjE0OC00ZjVhLTg3NDMtZmU1MTdiNGNlOTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE5MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZTlhZGJmYjJjNWQ0ZjQzNmFkNjc4MjY3MGI1Mzg5ZjFhMWRhMTUyMjg5MzAwYjIzMDA5ZmY4MmJlMzZmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdoLbyFUYP812OZJ71vZSLuaivKo0fTKzB4HLyol0-k)
> 
>     2. also need to fix icon position
>        ![image](https://private-user-images.githubusercontent.com/96265844/306380149-31264930-37c5-4c04-9382-7f56de8e65e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTY4NzksIm5iZiI6MTcwODQ1NjU3OSwicGF0aCI6Ii85NjI2NTg0NC8zMDYzODAxNDktMzEyNjQ5MzAtMzdjNS00YzA0LTkzODItN2Y1NmRlOGU2NWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE5MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDA5OTU1NTllZjk5YjUwYTJiOWM3OTZkMTU3ZjBhNzg5ODIyOTMzNzMzNWIyMGIwNGM1ZjRmMDM0YThmYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mmeBWBawMES-6SlKgYWsVNAdc9yUUlsBqAsQVPihjUQ)

1 on focus have other font weight check figma
2 in the chat the mentor said that there would be no problems with this pixel

2024-02-21 07:01 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2025-02-10 20:57 UTC, closed without merging