add task solution
mate-academy/layout_search-bar-airbnb pull request #4239
Opened 2024-04-19 18:37 UTC by Nazarin565

- [DEMO LINK](https://Nazarin565.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Nazarin565.github.io/layout_search-bar-airbnb/report/html_report/)

- [x] Icon implemented using background-image CSS property
- [x] Inputs are written inside of 'form' tag with correctly passed attributes
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-04-19 20:03 UTC, IvanFesenko requested changes
- Remove outline
![2024-04-19_22h59_24](https://github.com/mate-academy/layout_search-bar-airbnb/assets/61904995/feae22c6-1ec5-47a1-b1d6-d1b94d85237c)
- Text should be right side from icon
![2024-04-19_23h00_43](https://github.com/mate-academy/layout_search-bar-airbnb/assets/61904995/f3b0e595-6d99-4658-b680-93127cc90027)
![2024-04-19_23h00_39](https://github.com/mate-academy/layout_search-bar-airbnb/assets/61904995/ca09c035-7bd7-4125-bc68-624612f25fa3)

2024-04-19 22:06 UTC, Nazarin565 commented on src/style.css
> +  font-family: Avenir-Book, sans-serif;
@IvanFesenko i don't know, why github says that tests not passed, because when i write npm test in visual studio it passed done

2024-04-20 06:43 UTC, volodymyr-soltys97 requested changes
Hi, there is no styles here, you need to make a deploy again and check it on the demo link
<img width="373" alt="image" src="https://github.com/mate-academy/layout_search-bar-airbnb/assets/64750958/8a34d19b-12c1-4644-b8f6-71ee1a1ef7cb">

2024-04-20 06:43 UTC, volodymyr-soltys97 commented on src/style.css
> +html {
```suggestion
body {
```

2024-04-20 06:43 UTC, volodymyr-soltys97 commented on src/style.css
> +  padding: 0;
```suggestion
```

2024-04-20 07:37 UTC, SanyaBratashchuk approved these changes

2024-04-20 07:37 UTC, SanyaBratashchuk commented on src/style.css
> +  font-family: Avenir-Book, sans-serif;
```suggestion
  font-family: inherit;
```

2026-05-12 08:44 UTC, closed without merging