Develop
mate-academy/layout_search-bar-airbnb pull request #4599
Opened 2024-11-14 19:02 UTC by jessikamorais

- [DEMO LINK](https://jessikamorais.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://jessikamorais.github.io/layout_search-bar-airbnb/report/html_report/)

- [ ] Icon implemented using background-image CSS property
- [ ] Inputs are written inside of 'form' tag with correctly passed attributes
- [ ] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [ ] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-11-14 20:20 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `readme.md`
- `src/styles/style.css`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-14 21:40 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `readme.md`
- `src/styles/style.css`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-14 23:00 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `readme.md`
- `src/styles/style.css`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-11-18 13:28 UTC, joaorpereira commented on src/styles/style.css
> +  width:300px;
the search input should have full width, to accomplish that we need to set width to 100%

2024-11-18 13:29 UTC, joaorpereira commented on src/styles/style.css
> +  border:solid 1px;
it's missing the border color

2024-11-18 13:31 UTC, joaorpereira commented on src/index.html
> +      href="./styles/style.css"
@jessikamorais, you should not change the path of the styles.css file. The PR verification has pre-files selected to verify whether the code you are doing is correct or not. As you created a new file styled under the/styles folder, the verification is not working. Please move this code back to `href="style.css"` and move your whole CSS code inside that file to make code verification work properly.

2024-11-18 13:32 UTC, joaorpereira commented on src/style.css
> -/* add styles here */
@jessikamorais, you should add back this file and use this file to add your css code.

2024-11-18 13:35 UTC, joaorpereira commented
@jessikamorais these are the requirements of the task and they are missing in your solution:
- [ ] use images from [src/images](https://github.com/mate-academy/layout_search-bar-airbnb/blob/master/src/images)
- [ ] there must be two search bars
- [ ] search bar must stretch the full width
- [ ] distance between two search bars must be 20px
- [ ] the big search bar must have top indent 20px
- [ ] follow styles from the mock
- [ ] default font-weight must be 300
- [ ] a search bar has 3 state default, hover and focus
- [ ] don't use JavaScript
- [ ] use @font-face for fonts
- [ ] add attribute data-qa="big" for big search form, and data-qa="small" for small
- [ ] add attribute data-qa="keypress" to input in big search form

2024-11-18 13:38 UTC, joaorpereira commented on src/index.html
> +    <div class="search_bars">
wrap all elements inside a `form` tag

2024-11-18 13:41 UTC, joaorpereira requested changes
Pending requirements and build error

2024-11-18 19:31 UTC, jessikamorais commented on src/styles/style.css
> +  width: 900px;
I'm sorry, I did the PR before finishing the activity. But thanks for the tips, I'll fix it.

2024-11-19 13:43 UTC, jessikamorais commented
Code not finished yet

2024-11-22 14:30 UTC, joaorpereira commented
@jessikamorais I believe this is missing: 

`Inputs are written inside of 'form' tag with correctly passed attributes`

2024-11-22 14:46 UTC, joaorpereira requested changes

2024-11-22 14:46 UTC, joaorpereira commented on .prettierignore
> -/node_modules
add this file back

2024-11-22 14:46 UTC, joaorpereira commented on .prettierrc
> -        "endOfLine": "auto",
add this file back

2024-11-22 14:46 UTC, joaorpereira commented on src/index.html
> +    <div
wrap input element inside form component like:

```
     <form
        class="inputs__form"
        action="post"

        data-qa="keypress"
      >
        <input
          class="inputs__bigInput"
          type="text"
          data-qa="big"
          placeholder="Try “Los Angeles“"
        />
      </form>
```

2024-11-22 14:46 UTC, joaorpereira commented on src/index.html
> +    <div
same here

2024-11-22 14:46 UTC, joaorpereira commented on src/style.css
> +@font-face {
```
@font-face {
  font-family: 'Avenir';
  src: url(fonts/Avenir.ttc);
  font-weight: 300;
}

@font-face {
  font-family: 'Avenir';
  src: url(fonts/Avenir-Heavy.ttf);
  font-weight: 900;
}

@font-face {
  font-family: 'Avenir';
  src: url(fonts/Avenir-Book.ttf);
  font-weight: 400;
}
```

2024-11-22 14:46 UTC, joaorpereira commented on src/style.css
> +
.html {
  font-family: 'Avenir';
  font-weight: 300;
}

2024-11-22 14:46 UTC, joaorpereira commented on src/style.css
> +  font-family: AvenirFonte, Arial, sans-serif;
remove this line

2024-11-25 11:14 UTC, closed without merging