Solution
mate-academy/layout_search-bar-airbnb pull request #544
Opened 2021-05-03 22:51 UTC by vlad-moysieienko

[DEMO LINK](https://vlad-moisieienko.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://vlad-moisieienko.github.io/layout_search-bar-airbnb/report/html_report/)

2021-05-03 22:58 UTC, vlad-moysieienko commented
Я единственное не знаю почему не работает ссылка TEST REPORT LINK, так как я прописовал npm run deploy и по идеи все должно было работать

2021-05-03 23:05 UTC, vlad-moysieienko commented
![image](https://user-images.githubusercontent.com/80917931/116943941-31b88d80-ac7d-11eb-9440-fa557d23cf87.png)

2021-05-05 12:47 UTC, vpolets requested changes

2021-05-05 12:47 UTC, vpolets commented on src/index.html
> +    data-qa="big">
```suggestion
    <form
      class="form"
      method="post"
      data-qa="big"
    >
```

2021-05-05 12:47 UTC, vpolets commented on src/index.html
> +      class="search-bar search-bar-big"
є просто search-bar і search-bar--small модифікатор для нього який перевизначає поля з розмірами

2021-05-05 12:47 UTC, vpolets commented on src/index.html
> +      <img
поправ усюди форматування html

2021-05-05 12:47 UTC, vpolets commented on src/style.css
> +  font-family: "Avenir-Book";
```suggestion
  font-family: "Avenir";
```

2021-05-05 12:47 UTC, vpolets commented on src/style.css
> +  font-family: "Avenir-Heavy";
```suggestion
  font-family: "Avenir";
```

2021-05-05 12:47 UTC, vpolets commented on src/style.css
> +  box-sizing: border-box;
вкажи шрифт для усього html або body

2021-05-05 12:47 UTC, vpolets commented on src/style.css
> +  font-family: Avenir-book, sans-serif;
не повторюй те що можна винести в body

2021-05-05 12:47 UTC, vpolets commented on src/style.css
> +  font-weight: normal;
це дефолтні величини їх вказувати не треба

2021-05-05 12:47 UTC, vpolets commented on src/index.html
> +    >
картинка не несе ніякого смислового навантаження, просто додай її як background-image

2021-05-05 23:10 UTC, vlad-moysieienko commented
Я сделал все только я создал ветку Develop , а pull request делал на ветке master и немного несостыковочка вышла , что мне делать?
[DEMO LINK](https://vlad-moisieienko.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://vlad-moisieienko.github.io/layout_search-bar-airbnb/report/html_report/)

2021-05-05 23:13 UTC, vlad-moysieienko commented
ссылки не работают, и я не могу ничего сделать так как pull request был с другой ветки

2021-05-06 11:26 UTC, vkryvytskyy commented
> ссылки не работают, и я не могу ничего сделать так как pull request был с другой ветки

Сделай новый пулл реквест из ветки девелоп в мастер оригинального репозитория, а этот закрой

2021-05-06 11:26 UTC, vkryvytskyy requested changes
Открой ПР из ветки девелоп

2021-05-06 18:53 UTC, closed without merging