Search Bar
mate-academy/layout_search-bar-airbnb pull request #647
Opened 2021-06-21 09:26 UTC by anton-forzun

2021-06-22 13:12 UTC, vpolets requested changes
Не бачу градієнту який є в макеті

2021-06-22 13:12 UTC, vpolets commented on src/style.css
> +.search-iconB {
що означає приставка B?

2021-06-22 13:24 UTC, anton-forzun commented on src/style.css
> +.search-iconB {
B-big щоб не було однакового імені.

2021-06-22 13:32 UTC, anton-forzun commented on src/style.css
> +.search-iconB {
Що значить градієнт, це стилі які є в прикладі,?Я їх підставляв і воно щось не так виходить, я щось заплутався, з прикладу потрібно скопіювати всі стилі,6-ти пошуків чи тільки два пошуки зробити ,не можу зрозуміти суть завдання.

2021-06-22 14:30 UTC, vpolets submitted a review, later dismissed
Їх копіювати не треба, зробити по макету потрібно, має бути 2 search
1 звичайний і й менший
Далі показано як вони себе мають поводити при hover 
І при focus це їх різні стани

2021-06-23 12:41 UTC, mykola-yarchuk requested changes
great job, almost done 💪

2021-06-23 12:41 UTC, mykola-yarchuk commented on src/style.css
> +  box-sizing: border-box;
add `box-sizing` inside `*` selector

2021-06-23 12:41 UTC, mykola-yarchuk commented on src/style.css
> +  background-repeat: no-repeat;
create another class `search` (for example) with styles that the same for both search bars. don't repeat yourself.

2021-06-23 12:41 UTC, mykola-yarchuk commented on src/style.css
> +}
this styles the same for big and small search bar, move it to one class and use it on both of them

2021-06-25 07:40 UTC, mykola-yarchuk approved these changes
great

2021-07-01 08:43 UTC, closed without merging