Develop
mate-academy/layout_search-bar-airbnb pull request #654
Opened 2021-06-26 08:55 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/layout_search-bar-airbnb/)

2021-06-29 11:00 UTC, vkryvytskyy requested changes
![image](https://user-images.githubusercontent.com/38065883/123786072-f7b4e200-d8e1-11eb-9cdf-c0d7182c77d2.png)
Инпут должен быть по ширине на всю ширину этого блока, а не на ширину синего квадрата(сейчас фокусировка происходит только если кликнуть в синем квадрате)

2021-06-29 11:00 UTC, vkryvytskyy commented on src/style.css
> +  height: 42px;
У нас немає ніякого проміжного search, відповідно, чому має бути search2 і search?0 У нас є search-input та search-input--small (--small - модифікатор). Тому всі стилі які прописані для “великого” інпуту ми задаємо для всіх інпутів в цілому, а за допомогою модифіктора small міняємо тільки потрібні значення, щоб наш інпут став малим.

2021-06-29 11:00 UTC, vkryvytskyy commented on src/style.css
> +label {
Не стилизуй теги, используй классы

2021-06-29 11:00 UTC, vkryvytskyy commented on src/style.css
> +}
Не увеличивай специфичность селекторов

2021-09-26 11:47 UTC, Dinexpod commented on readme.md
>      - [TEST REPORT LINK](https://<your_account>.github.io/layout_search-bar-airbnb/report/html_report/)
ok

2021-09-26 14:53 UTC, Dinexpod commented on src/index.html
> +      class="search0">
угу) точно

2021-09-26 14:54 UTC, Dinexpod commented on src/style.css
> +.search0 {
сам удивился, ну на то время так решил) назову лучше big и я little

2021-09-26 15:16 UTC, Dinexpod commented on src/style.css
> +label {
ok

2026-05-10 22:09 UTC, closed without merging