home work
mate-academy/layout_search-bar-airbnb pull request #737
Opened 2021-07-25 19:28 UTC by Dmytryi-Bashlai

[DEMO LINK](https://Dmytryi-Bashlai.github.io/layout_search-bar-airbnb/)
[TEST REPORT LINK](https://Dmytryi-Bashlai.github.io/layout_search-bar-airbnb/report/html_report/)

2021-07-26 12:31 UTC, vkryvytskyy requested changes

2021-07-26 12:31 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://Dmytryi-Bashlai.github.io/layout_search-bar-airbnb/)
![image](https://user-images.githubusercontent.com/38065883/126988797-28cc803a-e726-4c9e-894c-348cbfb24653.png)
При фокусировке шрифт должен становиться более жирным, у тебя не становится

2021-07-26 12:31 UTC, vkryvytskyy commented on src/index.html
> +        >
Добавляй через бекграунд, или как псевдо элемент

2021-07-26 12:31 UTC, vkryvytskyy commented on src/index.html
> +        >
https://codepen.io/adskiy/pen/vYmJJVe
Вот пример

2021-07-26 12:31 UTC, vkryvytskyy commented on src/style.css
> +}
У нас немає ніякого проміжного search, відповідно, чому має бути великий і малий search? У нас є search-input та search-input--small (--small - модифікатор). Тому всі стилі які прописані для “великого” інпуту ми задаємо для всіх інпутів в цілому, а за допомогою модифіктора small міняємо тільки потрібні значення, щоб наш інпут став малим.

2021-07-26 12:57 UTC, Dmytryi-Bashlai commented on src/style.css
> +}
Понял, исправлю. Спасибо! Но есть вопрос по этому поводу, как на практике относятся к перезаписыванию стилей?
Спасибо!

2021-07-26 12:57 UTC, Dmytryi-Bashlai commented on src/index.html
> +        >
Понял, принял! Спасибо!

2021-07-26 12:57 UTC, Dmytryi-Bashlai commented on readme.md
> +- [DEMO LINK](https://Dmytryi-Bashlai.github.io/layout_search-bar-airbnb/)
![image](https://user-images.githubusercontent.com/70479612/126990524-83b7d5bc-a01d-417f-814f-512e0c841fe9.png)
У меня работает, или шрифт должен быть более жирным?

2021-07-29 16:15 UTC, Dmytryi-Bashlai commented
Можно пожалуйста подробней, что мне нужно исправить?
Спасибо.

2021-09-05 09:52 UTC, closed without merging