search bars was created
mate-academy/layout_search-bar-airbnb pull request #811
Opened 2021-08-30 15:48 UTC by Konsttantin

DEMO LINK: https://Konsttantin.github.io/layout_search-bar-airbnb/
TEST REPORT LINK: https://Konsttantin.github.io/layout_search-bar-airbnb/report/html_report/
Не понимаю, почему не проходит последний тест, если остальные работают, разница только в ширине экрана и никакого смещения фонового изображения не должно происходить по идее...

2021-09-01 12:19 UTC, vkryvytskyy requested changes

2021-09-01 12:19 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://Konsttantin.github.io/layout_search-bar-airbnb/)
![image](https://user-images.githubusercontent.com/38065883/131669506-e116e6e3-aec1-4f15-ae59-5c489a400973.png)
Вот какой цвет шрифта по умолчанию в дизайне
![image](https://user-images.githubusercontent.com/38065883/131669560-4000d468-c57d-45f4-8fd4-e2629bd538e8.png)
А вот какой у тебя
![image](https://user-images.githubusercontent.com/38065883/131669614-e79492aa-89cb-41f0-b1f4-fc2946d24143.png)
Плюс вот тут в правом нижнем углу иконки видно что у тебя там опять рендерится еще одна лупа

2021-09-01 12:19 UTC, vkryvytskyy commented on src/index.html
> +      class="search-bar__small"
```suggestion
      class="search-bar search-bar--small"
```
Это модификатор по БЭМу и должен еще быть общий класс, без модификатора, в котором будут общие стили для большого и маленького search-bar

2021-09-01 12:19 UTC, vkryvytskyy commented on src/style.css
> +}
Надо ли указывать font-weight: normal? Это значение по-умолчанию для font-weight

2021-09-01 12:44 UTC, Konsttantin commented on src/style.css
> +}
Да, но у меня для инпута стоит font-weight: bold и placeholder его наследует, поэтому я отдельно для него прописал

2021-09-01 16:00 UTC, Konsttantin commented on readme.md
> +- [DEMO LINK](https://Konsttantin.github.io/layout_search-bar-airbnb/)
Этот дефект в углу присутствует даже на референсном изображении из readme файла в репозитории задания. Я даже заново экспортировал из фигмы эту иконку, открыл её отдельно в браузере и всё равно есть этот странный фрагмент. Не понимаю как от него избавиться и откуда он берётся, ведь в фигме на макете лупа выглядит нормально.

2021-09-03 12:03 UTC, vkryvytskyy approved these changes

2021-09-03 12:03 UTC, vkryvytskyy commented on src/style.css
> +.search-bar__field:focus {
Чем отличается search-bar--field от search-bar__field?

2021-09-03 13:19 UTC, Konsttantin commented on src/style.css
> +.search-bar__field:focus {
Это моя ошибка, невнимательно переименовал классы, search-bar__field вовсе не должно быть в css

2025-01-19 15:39 UTC, closed without merging