for a review for the first time
mate-academy/layout_search-bar-airbnb pull request #839
Opened 2021-09-09 13:42 UTC by Artem18084

- [DEMO LINK](https://Artem18084.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Artem18084.github.io/layout_search-bar-airbnb/report/html_report/)

2021-09-09 15:09 UTC, VinnieJ-2k20 requested changes
Demo link and test report links are not working

2021-09-10 06:48 UTC, Artem18084 commented
- [DEMO LINK](https://Artem18084.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Artem18084.github.io/layout_search-bar-airbnb/report/html_report/)

2021-09-10 06:49 UTC, Artem18084 commented
- [DEMO LINK](https://Artem18084.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Artem18084.github.io/layout_search-bar-airbnb/report/html_report/)

2021-09-10 09:11 UTC, VinnieJ-2k20 requested changes
Focus styles work incorrectly.
Input should fill the form block completelyfor focus styles to work
![image](https://user-images.githubusercontent.com/60885495/132830261-90a364ff-0e52-4082-b8e5-aa176fbde280.png)

Also, lots of common styles for big and small elements are used. Put them in common classes for form, input or image.

2021-09-10 09:11 UTC, VinnieJ-2k20 commented on src/style.css
> +} */
Don't leave commented code.

2021-09-10 18:04 UTC, Artem18084 commented
- [DEMO LINK](https://Artem18084.github.io/layout_search-bar-airbnb/)
- [TEST REPORT LINK](https://Artem18084.github.io/layout_search-bar-airbnb/report/html_report/)

2021-09-11 05:28 UTC, VinnieJ-2k20 approved these changes

2023-04-01 20:36 UTC, closed without merging