First attempt, need some advise
mate-academy/layout_search-bar-airbnb pull request #872
Opened 2021-10-11 13:19 UTC by kommoddo

2021-10-12 18:47 UTC, vkryvytskyi requested changes

2021-10-12 18:47 UTC, vkryvytskyy commented on src/style.css
> +}
У нас немає ніякого проміжного search, відповідно, чому має бути великий і малий search? У нас є search-input та search-input--small (--small - модифікатор). Тому всі стилі які прописані для “великого” інпуту ми задаємо для всіх інпутів в цілому, а за допомогою модифіктора small міняємо тільки потрібні значення, щоб наш інпут став малим.

2021-10-12 18:47 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://kommoddo.github.io/layout_search-bar-airbnb/)
![image](https://user-images.githubusercontent.com/38065883/137011993-f7c41822-6306-49fb-98c4-c059b804efb9.png)
Цвет текста в плейсхолдере не соответствует дизайну
При фокусировке в инпуте должен на фон устанавливаться linear-gradient, я тут его не вижу

2021-10-18 08:28 UTC, vkryvytskyi submitted a review, later dismissed

2021-10-18 08:28 UTC, vkryvytskyy commented on src/style.css
> +  outline: 1px solid #e1e7ed;
Не уверен что там должен появляться этот outline, и linear-gradient'a все еще нет

2021-10-25 11:50 UTC, varseniuk approved these changes
👍

2026-06-22 05:02 UTC, closed without merging